import {useEffect,useState} from 'react';
import {supabase} from '@/lib/supabase';
import {Card} from '@/components/ui/Card';
import {Button} from '@/components/ui/Button';
export function DataSubAvailabilityReview(){
 const [rows,setRows]=useState<any[]>([]),[providers,setProviders]=useState<any[]>([]),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[form,setForm]=useState({provider:'',service:'DATA',network:'MTN',available:false,evidence:''});
 async function load(){if(!supabase)return;const [a,b]=await Promise.all([supabase.from('datasub_network_availability').select('*').order('checked_at',{ascending:false}),supabase.from('datasub_providers').select('id,code').order('code')]);if(a.error||b.error){setMessage('Availability reviews could not be loaded. Approval permission is required.');return;}setRows(a.data||[]);setProviders(b.data||[]);}
 useEffect(()=>{void load()},[]);
 async function save(){if(!supabase||busy)return;setBusy(true);const r=await supabase.rpc('review_datasub_network_availability',{p_provider:form.provider,p_service:form.service,p_network:form.network,p_available:form.available,p_evidence:form.evidence});setBusy(false);if(r.error){setMessage('Review was not saved. Confirm your approval permission and provide evidence of the current provider status.');return;}setMessage('Availability updated. Customer services and purchase checks now use this status.');setForm(v=>({...v,evidence:''}));await load();}
 return <Card><h3 className="font-bold">Service availability reviews</h3><p className="mt-2 text-sm text-muted">A funded provider account does not confirm that every network is operating. Check its current service status before reopening an unavailable network. Changes immediately update customer availability without changing catalogue prices or route configuration.</p><div className="mt-3 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{rows.map(row=><div key={`${row.provider_id}:${row.service_type}:${row.network}`} className="rounded-xl border p-3 text-sm"><b>{providers.find(p=>p.id===row.provider_id)?.code||'Provider'} · {row.network} · {row.service_type}</b><p className={row.available?'text-emerald-700':'text-amber-700'}>{row.available?'Available':'Unavailable'}</p><p className="mt-1 text-xs text-muted">{row.evidence_source}</p></div>)}</div><form onSubmit={e=>{e.preventDefault();void save()}} className="mt-4 grid gap-3 sm:grid-cols-2"><label className="text-sm">Provider<select required className="mt-1 w-full rounded border p-2" value={form.provider} onChange={e=>setForm({...form,provider:e.target.value})}><option value="">Select provider</option>{providers.map(p=><option key={p.id} value={p.id}>{p.code}</option>)}</select></label><label className="text-sm">Service<select className="mt-1 w-full rounded border p-2" value={form.service} onChange={e=>setForm({...form,service:e.target.value})}>{['DATA','AIRTIME','CABLE','ELECTRICITY','EXAM'].map(v=><option key={v}>{v}</option>)}</select></label><label className="text-sm">Network<input required className="mt-1 w-full rounded border p-2" value={form.network} onChange={e=>setForm({...form,network:e.target.value.toUpperCase()})}/></label><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={form.available} onChange={e=>setForm({...form,available:e.target.checked})}/>Confirmed available</label><label className="text-sm sm:col-span-2">Review evidence<textarea required minLength={10} className="mt-1 w-full rounded border p-2" value={form.evidence} onChange={e=>setForm({...form,evidence:e.target.value})}/></label><Button disabled={busy||!form.provider}>{busy?'Saving…':'Save reviewed status'}</Button></form>{message&&<p role="status" className="mt-3 text-sm">{message}</p>}</Card>;
}
