import {useCallback,useEffect,useRef,useState} from 'react';
import {supabase} from '@/lib/supabase';
import {useAuth} from '@/context/AuthContext';
type Row=Record<string,any>;
const tables:Record<string,string>={schoolpro_subscription:'schoolpro_subscription_intents',consult:'consult_invoices',engineering:'engineering_invoices',print:'print_invoices',host:'host_invoices',fabrication:'business_invoices',compute:'business_invoices',academy:'business_invoices',digital_business:'business_invoices',business_centre:'business_invoices'};
const field='mt-1 w-full rounded-lg border p-3';
export function InvoiceWorkbench(){
 const {user}=useAuth();const generation=useRef(0);const [platform,setPlatform]=useState('consult'),[rows,setRows]=useState<Row[]>([]),[proofs,setProofs]=useState<Row[]>([]),[selected,setSelected]=useState<Row|null>(null),[loading,setLoading]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('');
 const [form,setForm]=useState({name:'',description:'',amount:'',reason:''});
 const load=useCallback(async()=>{const version=++generation.current;setRows([]);setProofs([]);setSelected(null);setError('');if(!supabase||!user)return;setLoading(true);try{
  let query=supabase.from(tables[platform]).select(platform in tables&&tables[platform]==='business_invoices'?'*,business_orders!inner(unit_code,title,requirements)':'*').order('created_at',{ascending:false}).limit(200);
  if(tables[platform]==='business_invoices')query=query.eq('business_orders.unit_code',platform);
  const [invoices,transfers]=await Promise.all([query,supabase.from('direct_transfer_submissions').select('id,invoice_id,amount,status,customer_reference,proof_storage_path').eq('platform_code',platform).in('status',['pending','awaiting_verification'])]);
  if(version!==generation.current)return;if(invoices.error||transfers.error)throw invoices.error||transfers.error;setRows(invoices.data||[]);setProofs(transfers.data||[]);
 }catch(e){if(version===generation.current)setError((e as Error).message);}finally{if(version===generation.current)setLoading(false);}},[platform,user?.id]);
 useEffect(()=>{void load();return()=>{generation.current++;};},[load]);
 const choose=(row:Row)=>{setSelected(row);setNotice('');setError('');setForm({name:row.service_name||row.title||'',description:row.service_description||'',amount:String(row.amount),reason:''});};
 async function act(action:'cancel'|'regenerate'|'revise'){
  if(!supabase||!selected||busy)return;setError('');setNotice('');if(form.reason.trim().length<3){setError('Enter a reason for this change.');return;}
  setBusy(true);try{const r=platform==='schoolpro_subscription'?await supabase.rpc('manage_schoolpro_subscription_invoice',{p_invoice:selected.id,p_action:action,p_version:selected.updated_at,p_reason:form.reason.trim()}):await supabase.rpc('manage_service_invoice',{p_platform:platform,p_invoice:selected.id,p_action:action,p_version:selected.updated_at,p_reason:form.reason.trim(),p_name:form.name,p_description:form.description,p_amount:action==='revise'?Number(form.amount):null});if(r.error)throw r.error;setNotice(action==='revise'?'Revision sent to the customer. Payment is paused until they accept.':action==='cancel'?'Invoice cancelled. Its history is preserved.':'Replacement generated for the same service. Drafts still require commercial approval before payment.');await load();}catch(e){setError((e as Error).message);}finally{setBusy(false);}
 }
 async function verify(proof:Row){if(!supabase||busy||form.reason.trim().length<8){setError('Enter a bank-statement verification note before marking paid.');return;}setBusy(true);setError('');try{const r=await supabase.rpc('review_direct_bank_transfer',{p_submission:proof.id,p_decision:'approved',p_note:form.reason.trim()});if(r.error)throw r.error;setNotice('Bank transfer verified and invoice settled. Service activation follows its existing provisioning workflow.');await load();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 async function receipt(proof:Row){if(!supabase||!proof.proof_storage_path)return;const r=await supabase.storage.from('direct-transfer-proofs').createSignedUrl(proof.proof_storage_path,60);if(r.error){setError(r.error.message);return;}window.open(r.data.signedUrl,'_blank','noopener,noreferrer');}
 const unpaid=selected&&Number(selected.amount_paid||0)===0&&!selected.paid_at&&!['paid','part_paid','partial'].includes(selected.status);
 return <section className="space-y-4 rounded-2xl border bg-white p-4 sm:p-6"><h2 className="text-xl font-bold">Service invoice controls</h2><p className="text-sm">Edit unpaid invoices through a customer-approved revision. Mark paid only after checking the receipt against the receiving bank statement. Mark unpaid generates a replacement only from a cancelled invoice.</p>
 <label className="block">Platform<select className={field} disabled={busy} value={platform} onChange={e=>{setNotice('');setPlatform(e.target.value);}}>{Object.keys(tables).map(x=><option key={x} value={x}>{x.replaceAll('_',' ')}</option>)}</select></label>
 {error&&<p role="alert" className="rounded-lg bg-red-50 p-3 text-red-900">{error}</p>}{notice&&<p role="status" className="rounded-lg bg-green-50 p-3">{notice}</p>}
 <button type="button" className="min-h-11 rounded-lg border px-4" disabled={busy||loading} onClick={()=>void load()}>Refresh invoices</button>
 {loading?<p role="status">Loading invoices…</p>:<div className="grid gap-3 md:grid-cols-2">{rows.map(row=><button type="button" key={row.id} disabled={busy} aria-pressed={selected?.id===row.id} className={`min-w-0 rounded-xl border p-4 text-left ${selected?.id===row.id?'border-blue-700 bg-blue-50':''}`} onClick={()=>choose(row)}><b className="block break-all">{row.invoice_number||row.reference}</b><span className="block">{row.service_name||row.title||(platform==='schoolpro_subscription'?'Annual SchoolPro subscription':'Service invoice')}</span><span className="block">{row.currency} {Number(row.amount).toLocaleString()} · {row.status}</span></button>)}{!rows.length&&<p>No invoices are available for your platform permissions.</p>}</div>}
 {selected&&<div className="space-y-3 rounded-xl border p-4"><h3 className="font-bold break-all">{selected.invoice_number||selected.reference}</h3>{platform==='schoolpro_subscription'&&<p>SchoolPro annual prices come from the published subscription plan. Regeneration retains the same school, payer and plan.</p>}<p className="text-sm break-all">Service reference: {selected.project_id||selected.order_id||selected.school_id||selected.id}</p>{selected.replaces_invoice_id&&<p className="text-sm break-all">Replaces cancelled invoice: {selected.replaces_invoice_id}</p>}<fieldset disabled={busy} className="grid gap-3 sm:grid-cols-2"><label>Service name<input className={field} value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></label><label>Amount ({selected.currency||'NGN'})<input disabled={platform==='schoolpro_subscription'} type="number" min="0.01" step="0.01" className={field} value={form.amount} onChange={e=>setForm({...form,amount:e.target.value})}/></label><label className="sm:col-span-2">Service details<textarea className={field} rows={3} value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/></label><label className="sm:col-span-2">Reason / bank-statement verification note<textarea className={field} rows={3} value={form.reason} onChange={e=>setForm({...form,reason:e.target.value})}/></label>
 <button type="button" className="min-h-11 rounded-lg border p-3" disabled={platform==='schoolpro_subscription'||!unpaid||!['issued','unpaid','overdue','awaiting_payment'].includes(selected.status)} onClick={()=>void act('revise')}>Send invoice revision</button><button type="button" className="min-h-11 rounded-lg border p-3" disabled={!unpaid||selected.status==='cancelled'} onClick={()=>void act('cancel')}>Mark cancelled</button><button type="button" className="min-h-11 rounded-lg border p-3" disabled={!unpaid||selected.status!=='cancelled'} onClick={()=>void act('regenerate')}>Regenerate / mark unpaid</button>
 {proofs.filter(p=>p.invoice_id===selected.id).map(p=><div key={p.id} className="space-y-2 rounded-lg border p-3 sm:col-span-2"><p>Pending proof: {p.customer_reference} · {p.amount}</p><button type="button" className="min-h-11 rounded-lg border px-4" onClick={()=>void receipt(p)}>View receipt</button><button type="button" className="ml-2 min-h-11 rounded-lg bg-blue-700 px-4 text-white" onClick={()=>void verify(p)}>Verify bank statement & mark paid</button></div>)}</fieldset></div>}
 </section>;
}
