import { useEffect, useState } from "react";
import { Link } from "react-router-dom";
import { ArrowRight } from "lucide-react";
import { supabase } from "@/lib/supabase";
import { Button } from "@/components/ui/Button";

export type ManagedPageKey = "corporate"|"datasub"|"schoolpro"|"consult"|"host"|"engineering"|"business_centre"|"print"|"fabrication"|"compute"|"academy"|"digital_business";
type Block={id:string;page_path:string;section_key:string;eyebrow:string|null;title:string;subtitle:string|null;body:string|null;image_url:string|null;background_image_url:string|null;cta_label:string|null;cta_link:string|null;secondary_cta_label:string|null;secondary_cta_link:string|null;content_settings:any;layout:"split"|"centered"|"cards"|"banner";theme:"light"|"navy"|"blue"|"emerald"|"purple"|"orange";sort_order:number};
const themes={light:"bg-white text-ink",navy:"bg-navy-900 text-white",blue:"bg-gradient-to-br from-royal-700 to-sky-500 text-white",emerald:"bg-gradient-to-br from-emerald-600 to-cyan-500 text-white",purple:"bg-gradient-to-br from-purple-700 to-indigo-600 text-white",orange:"bg-gradient-to-br from-orange-500 to-pink-600 text-white"};

export function ManagedContentSections({pageKey}:{pageKey:ManagedPageKey}){
 const [blocks,setBlocks]=useState<Block[]>([]);
 useEffect(()=>{let active=true;async function load(){if(!supabase)return;const {data}=await supabase.from("site_content_blocks").select("id,page_path,section_key,eyebrow,title,subtitle,body,image_url,background_image_url,cta_label,cta_link,secondary_cta_label,secondary_cta_link,content_settings,layout,theme,sort_order").eq("page_key",pageKey).eq("page_path",window.location.pathname||"/").eq("is_visible",true).neq("section_key","hero").order("sort_order");if(active)setBlocks((data||[]) as Block[]);}void load();return()=>{active=false};},[pageKey]);
 if(!blocks.length)return null;
 return <div data-managed-content={pageKey}>{blocks.map(block=>{const settings=block.content_settings||{};const centered=block.layout==="centered"||block.layout==="banner"||settings.textAlign==="center";const link=(label:string|null,href:string|null,secondary=false)=>label&&href?(href.startsWith("/")?<Link to={href}><Button variant={secondary?"secondary":undefined} rightIcon={<ArrowRight className="h-4 w-4"/>}>{label}</Button></Link>:<a href={href} target="_blank" rel="noreferrer"><Button variant={secondary?"secondary":undefined} rightIcon={<ArrowRight className="h-4 w-4"/>}>{label}</Button></a>):null;const content=<div style={{fontFamily:settings.fontFamily||undefined,textAlign:settings.textAlign||undefined,maxWidth:settings.maxWidth?settings.maxWidth:undefined}} className={centered?"mx-auto":"max-w-2xl"}>{block.eyebrow&&<p className="mb-3 text-xs font-extrabold uppercase tracking-[.2em] opacity-80">{block.eyebrow}</p>}<h2 style={{fontSize:settings.fontSize?settings.fontSize:undefined}} className="text-3xl font-extrabold lg:text-5xl">{block.title}</h2>{block.subtitle&&<p className="mt-3 text-xl font-semibold opacity-90">{block.subtitle}</p>}{block.body&&<p className="mt-5 text-base leading-7 opacity-85 lg:text-lg">{block.body}</p>}<div className="mt-7 flex flex-wrap gap-3">{link(block.cta_label,block.cta_link)}{link(block.secondary_cta_label,block.secondary_cta_link,true)}</div></div>;return <section key={block.id} id={block.section_key} className="px-6 lg:px-10" style={{paddingTop:settings.paddingY||64,paddingBottom:settings.paddingY||64,backgroundImage:block.background_image_url?`url(${block.background_image_url})`:undefined,backgroundSize:'cover',backgroundPosition:'center'}}><div style={{maxWidth:settings.maxWidth||1280}} className={`mx-auto overflow-hidden rounded-3xl ${themes[block.theme]} ${block.layout==="banner"?"p-10 lg:p-16":"p-8 lg:p-12"}`}><div className={block.layout==="split"&&block.image_url?"grid items-center gap-10 lg:grid-cols-2":""}>{content}{block.image_url&&<img src={block.image_url} alt={block.title} loading="lazy" decoding="async" className={`block h-auto w-full rounded-2xl object-contain ${block.layout==="split"?"":"mt-8"}`}/>}</div></div></section>})}</div>;
}
