import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import{createClient}from"jsr:@supabase/supabase-js@2";
const H={"content-type":"application/json","cache-control":"no-store","access-control-allow-origin":"*"};const json=(b:unknown,s=200)=>new Response(JSON.stringify(b),{status:s,headers:H});
const base="https://api.billstack.co/v2";const secret=()=>Deno.env.get("BILLSTACK_SECRET_KEY")||"";
const admin=()=>createClient(Deno.env.get("SUPABASE_URL")!,Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!,{auth:{persistSession:false}});
const pick=(o:any,...ks:string[])=>{for(const k of ks){const v=k.split(".").reduce((a,x)=>a?.[x],o);if(v!==undefined&&v!==null&&v!=="")return v}};
class ProviderError extends Error{status:number;code:string;constructor(message:string,status:number,code="BILLSTACK_PROVIDER_ERROR"){super(message);this.status=status;this.code=code}}
async function call(path:string,body:any){const key=secret();if(!key)throw new ProviderError("BillStack API key is not configured.",503,"BILLSTACK_NOT_CONFIGURED");const r=await fetch(base+path,{method:"POST",headers:{authorization:"Bearer "+key,"content-type":"application/json"},body:JSON.stringify(body)});const raw=await r.text();let x:any={};try{x=raw?JSON.parse(raw):{}}catch{x={message:raw.slice(0,300)}}const msg=String(pick(x,"message","error","data.message")||("BillStack returned HTTP "+r.status));if(!r.ok){console.error("BillStack provider rejection",{path,http_status:r.status,message:msg.slice(0,300)});throw new ProviderError(msg,r.status)}return x}
Deno.serve(async(req)=>{if(req.method==="OPTIONS")return new Response(null,{status:204,headers:{...H,"access-control-allow-headers":"authorization,apikey,content-type,x-client-info,x-supabase-api-version","access-control-allow-methods":"POST,OPTIONS"}});if(req.method!=="POST")return json({error:"method_not_allowed"},405);
const db=admin(),jwt=req.headers.get("authorization")?.replace(/^Bearer\s+/i,"");if(!jwt)return json({error:"authentication_required"},401);const{data:{user}}=await db.auth.getUser(jwt);if(!user)return json({error:"authentication_required"},401);
const body=await req.json().catch(()=>null)as any;if(!body)return json({error:"invalid_payload"},400);const action=String(body.action||"list");
if(action==="list"){const{data,error}=await db.from("virtual_accounts").select("id,provider,platform_code,merchant_reference,account_number,account_name,bank_name,bank_id,status,is_customer_visible,created_at").eq("user_id",user.id).eq("provider","billstack").eq("is_customer_visible",true);return error?json({error:error.message},400):json({data:data||[]})}
if(action==="create"){const bank=String(body.bank||"").toUpperCase();const{data:cfg}=await db.from("payment_provider_banks").select("bank_code,bank_name,enabled,customer_enabled,requires_identity,payment_providers!inner(code)").eq("payment_providers.code","billstack").eq("bank_code",bank).maybeSingle();if(!cfg?.enabled||!cfg.customer_enabled)return json({error:"bank_not_available"},403);
const{data:profile}=await db.from("profiles").select("email,first_name,last_name,phone").eq("id",user.id).maybeSingle();if(!profile?.email||!profile.first_name||!profile.last_name||!profile.phone)return json({error:"profile_incomplete",message:"Complete first name, last name, email and phone before activating a funding account."},422);
const platform=String(body.platform_code||"corporate").toLowerCase();if(!["corporate","datasub","schoolpro","host","consult","engineering","print","fabrication","compute","academy","digital_business"].includes(platform))return json({error:"platform_not_available"},403);const suffix=platform==="schoolpro"?"-SCH":platform==="host"?"-HOST":platform==="consult"?"-CONS":platform==="engineering"?"-ENG":platform==="print"?"-PRINT":platform==="fabrication"?"-FAB":platform==="compute"?"-CMP":platform==="academy"?"-ACA":platform==="digital_business"?"-DGT":"";const ref=`IHL-${user.id.replaceAll("-","").slice(0,20).toUpperCase()}-${bank}${suffix}`;const{data:existing}=await db.from("virtual_accounts").select("*").eq("provider","billstack").eq("merchant_reference",ref).maybeSingle();if(existing?.account_number)return json({data:existing,status:"existing"});
const idType=String(body.idType||"").toLowerCase(),idNumber=String(body.idNumber||"").trim();if(cfg.requires_identity&&(!["nin","bvn"].includes(idType)||!idNumber))return json({error:"identity_required",message:"PalmPay requires NIN or BVN verification. Identity is submitted directly to BillStack and is not stored by IHLink."},422);
let x:any;try{x=await call("/thirdparty/generateVirtualAccount/",{reference:ref,email:profile.email,phone:profile.phone,firstName:profile.first_name,lastName:profile.last_name,bank,...(cfg.requires_identity?{idType,idNumber}:{})})}catch(e){const pe=e as any,msg=String(pe?.message||"");if(/reference\s+already\s+exist/i.test(msg)){try{x=await call("/thirdparty/getVirtualAccount/",{reference:ref})}catch(re){const rpe=re as any;return json({error:rpe?.code||"billstack_recovery_failed",message:String(rpe?.message||"Existing BillStack account could not be recovered."),provider_status:typeof rpe?.status==="number"?rpe.status:undefined},502)}}else{return json({error:pe?.code||"billstack_provider_error",message:msg||"BillStack request failed",provider_status:typeof pe?.status==="number"?pe.status:undefined},pe?.code==="BILLSTACK_NOT_CONFIGURED"?503:502)}}
if(x?.status===false){const appMsg=String(x?.message||x?.error||"BillStack could not reserve the account.");if(/reference\s+already\s+exist/i.test(appMsg)){try{x=await call("/thirdparty/getVirtualAccount/",{reference:ref})}catch(re){const rpe=re as any;return json({error:rpe?.code||"billstack_recovery_failed",message:String(rpe?.message||"Existing BillStack account could not be recovered."),provider_status:typeof rpe?.status==="number"?rpe.status:undefined},502)}}else return json({error:"billstack_provider_error",message:appMsg},502)}
const d=pick(x,"data","result")||x,accountList=Array.isArray(d?.account)?d.account:[],a=accountList.find((v:any)=>String(v?.bank_id||v?.bank||"").toUpperCase()===bank)||accountList[0]||d,acct=String(pick(a,"account_number","accountNumber","nuban")||""),name=String(pick(a,"account_name","accountName")||""),providerRef=String(pick(d,"reference","provider_reference","id")||ref),bankId=String(pick(a,"bank_id","bankId","bank_code")||bank),providerBankName=String(pick(a,"bank_name","bankName")||cfg.bank_name);if(!acct)return json({error:"provider_response_incomplete",message:String(x?.message||"BillStack accepted the request but returned no virtual account number.")},502);
const row={user_id:user.id,provider:"billstack",platform_code:platform,merchant_reference:ref,provider_reference:providerRef,account_number:acct,account_name:name,bank_name:providerBankName,bank_id:bankId,status:"active",is_customer_visible:true,updated_at:new Date().toISOString()};const{data,error}=await db.from("virtual_accounts").upsert(row,{onConflict:"provider,merchant_reference"}).select().single();return error?json({error:error.message},400):json({data},201)}
if(action==="get"){const bank=String(body.bank||"").toUpperCase();const platform=String(body.platform_code||"corporate").toLowerCase();const suffix=platform==="schoolpro"?"-SCH":platform==="host"?"-HOST":platform==="consult"?"-CONS":platform==="engineering"?"-ENG":platform==="print"?"-PRINT":platform==="fabrication"?"-FAB":platform==="compute"?"-CMP":platform==="academy"?"-ACA":platform==="digital_business"?"-DGT":"";const ref=`IHL-${user.id.replaceAll("-","").slice(0,20).toUpperCase()}-${bank}${suffix}`;const{data:local}=await db.from("virtual_accounts").select("*").eq("provider","billstack").eq("merchant_reference",ref).maybeSingle();if(local)return json({data:local});try{const x=await call("/thirdparty/getVirtualAccount/",{reference:ref});return json({data:pick(x,"data","result")||x})}catch(e){return json({error:String((e as Error).message)},502)}}
if(action==="deactivate"){const id=String(body.id||"");const{data:va}=await db.from("virtual_accounts").select("*").eq("id",id).maybeSingle();const{data:p}=await db.from("profiles").select("role").eq("id",user.id).maybeSingle();if(!va||!["super_admin","finance"].includes(String(p?.role)))return json({error:"permission_denied"},403);try{await call("/thirdparty/deactivateVirtualAccount/",{reference:va.merchant_reference});await db.from("virtual_accounts").update({status:"deactivated",updated_at:new Date().toISOString()}).eq("id",id);return json({status:true})}catch(e){return json({error:String((e as Error).message)},502)}}
return json({error:"unsupported_action"},400)});
