import { useEffect, useMemo, useState } from 'react';
import { Link } from 'react-router-dom';
import { ArrowRight, Database, RefreshCw } from 'lucide-react';
import { ModulePage } from '@/components/ModulePage';
import { Card } from '@/components/ui/Card';
import { adminSections } from './adminShared';
import { supabase } from '@/lib/supabase';
import { useAuth } from '@/context/AuthContext';
import { openPlatformWithHandoff } from '@/lib/platformHandoff';

type MetricDef={label:string;table:string;filter?:[string,string|boolean];href?:string};
type ModuleDef={title:string;desc:string;action:string;metrics:MetricDef[];links:{label:string;href:string;description:string}[]};

const defs:Record<string,ModuleDef>={
 products:{title:'Products & Services',desc:'Live overview of IHLink service catalogues and operational products.',action:'Review Platforms',metrics:[
  {label:'DataSub Products',table:'datasub_products',filter:['is_active',true],href:'/admin/datasub'},
  {label:'Hosting Plans',table:'host_plans',filter:['is_active',true],href:'/admin/host'},
  {label:'Schools',table:'schoolpro_schools',href:'/admin/schoolpro'},
  {label:'Service Access',table:'customer_service_access',href:'/admin/customers'},{label:'Business Services',table:'business_catalog',filter:['is_active',true],href:'/admin/business-centre'},{label:'Business Orders',table:'business_orders',href:'/admin/business-centre'},{label:'Academy Courses',table:'academy_courses',filter:['is_active',true],href:'/admin/academy'}],
  links:[{label:'DataSub Control',href:'/admin/datasub',description:'Products, pricing, providers and reseller operations.'},{label:'SchoolPro Control',href:'/admin/schoolpro',description:'Schools, academics, results and access.'},{label:'Hosting Control',href:'/admin/host',description:'Hosting plans, domains, orders and services.'},{label:'Consult Control',href:'/admin/consult',description:'Requests, quotations and consulting projects.'},{label:'Engineering Control',href:'/admin/engineering',description:'Engineering requests, projects and field operations.'},{label:'Business & Innovation',href:'/admin/business-centre',description:'Business Centre operations and fulfilment.'},{label:'Print & Branding',href:'/admin/print',description:'Print and branding orders.'},{label:'3D & Fabrication',href:'/admin/fabrication',description:'Fabrication and prototype jobs.'},{label:'AI & Compute',href:'/admin/compute',description:'AI and compute workloads.'},{label:'Academy',href:'/admin/academy',description:'Courses, enrolments and learning operations.'},{label:'Digital Business Centre',href:'/admin/digital-business',description:'Digital business service requests.'}]},
 datasub:{title:'DataSub Administration',desc:'Live DataSub catalogue, transactions, wallets, resellers and provider operations.',action:'Manage DataSub',metrics:[
  {label:'Active Products',table:'datasub_products',filter:['is_active',true]},{label:'Transactions',table:'datasub_transactions'},{label:'Wallets',table:'datasub_wallets'},{label:'Resellers',table:'datasub_reseller_accounts'}],
  links:[{label:'Products & Pricing',href:'/datasub/pricing',description:'Review the customer-facing live product catalogue.'},{label:'Developer API',href:'/datasub/developer',description:'Review API products and developer access.'},{label:'DataSub Dashboard',href:'/datasub/dashboard',description:'Open the operational DataSub dashboard.'}]},
 schoolpro:{title:'SchoolPro Control Centre',desc:'IHLink-wide live control surface for schools, subscriptions, students, admissions, academics, CBT, results, finance, managed websites and document-template operations.',action:'Manage SchoolPro',metrics:[
  {label:'Schools',table:'schoolpro_schools'},{label:'Subscriptions',table:'schoolpro_subscriptions'},{label:'Students',table:'schoolpro_students'},{label:'Staff & Members',table:'schoolpro_members'},{label:'Admissions',table:'schoolpro_admissions'},{label:'Results',table:'schoolpro_results'},{label:'CBT Tests',table:'schoolpro_cbt_tests'},{label:'Invoices',table:'schoolpro_invoices'},{label:'Document Templates',table:'schoolpro_document_templates'},{label:'Issued Documents',table:'schoolpro_document_issues'},{label:'Custom Web Requests',table:'schoolpro_custom_requests'},{label:'Email Queue',table:'schoolpro_email_queue'},{label:'Library Books',table:'schoolpro_library_books'},{label:'Transport Routes',table:'schoolpro_transport_routes'},{label:'Hostel Rooms',table:'schoolpro_hostel_rooms'},{label:'Inventory Assets',table:'schoolpro_inventory_assets'},{label:'Payroll Records',table:'schoolpro_payroll_records'}],
  links:[{label:'School Administration',href:'/schoolpro/admin-dashboard',description:'Open the school administration workspace and operational modules.'},{label:'Students & Enrollment',href:'/schoolpro/students',description:'Review enrolled students and school records.'},{label:'Admissions',href:'/schoolpro/admissions',description:'Applications, verification, offers, entrance CBT and enrollment.'},{label:'Results & Assessment',href:'/schoolpro/results',description:'Assessment standards, scores, approvals and result workflows.'},{label:'Result Management',href:'/schoolpro/result-management',description:'Open the dedicated result-management workspace.'},{label:'Broadsheets & Reports',href:'/schoolpro/broadsheet',description:'Positions, publication and advanced academic reporting.'},{label:'CBT Management',href:'/schoolpro/cbt',description:'Create tests, control eligibility, review attempts and mark theory responses.'},{label:'Question Bank',href:'/schoolpro/question-bank',description:'Open the dedicated question-bank workspace for creating and maintaining CBT questions.'},{label:'Fees & Finance',href:'/schoolpro/fees',description:'Fee structures, invoices, offline receipts and debt controls.'},{label:'Result Templates',href:'/schoolpro/result-templates',description:'Configure editable Excel report-card templates and mappings.'},{label:'Document & Certificate Studio',href:'/schoolpro/documents',description:'PDF/DOCX certificate, admission-letter, transcript, ID and custom document templates.'},{label:'Branding & School Portal',href:'/schoolpro/settings',description:'School identity, portal branding and managed website configuration.'},{label:'School Operations',href:'/schoolpro/operations',description:'Library, transport, hostel, inventory, payroll, leave, clinic, discipline, promotions, lesson notes and academic documents.'},{label:'Classes, Subjects & Teachers',href:'/schoolpro/classes',description:'Classes, arms, subjects, teacher assignment and academic structure.'},{label:'Attendance & Timetable',href:'/schoolpro/attendance',description:'Daily attendance and timetable operations.'},{label:'Assignments & Announcements',href:'/schoolpro/assignments',description:'Learning tasks and school communication workflows.'},{label:'Parents & Guardians',href:'/schoolpro/parents',description:'Guardian records, student links and parent portal access.'},{label:'Staff & Access',href:'/schoolpro/staff',description:'School staff, memberships, roles and access control.'},{label:'Roles & Permissions',href:'/schoolpro/roles-permissions',description:'School-level operational permission management.'},{label:'Custom Website Requests',href:'/admin/schoolpro/custom-requests',description:'IHLink quotation, approval and provisioning queue.'}]},
 consult:{title:'Consult Administration',desc:'Live consulting requests, quotations, projects and client operations.',action:'Manage Consult',metrics:[
  {label:'Requests',table:'consult_requests'},{label:'Quotations',table:'consult_quotations'},{label:'Projects',table:'consult_projects'},{label:'Payments',table:'consult_payments'}],
  links:[{label:'Consult Dashboard',href:'/consult/dashboard',description:'Open consulting operations.'},{label:'Client Requests',href:'/consult/requests',description:'Review genuine customer requests.'}]},
 engineering:{title:'Engineering Administration',desc:'Live engineering requests, projects, equipment and support operations.',action:'Manage Engineering',metrics:[
  {label:'Requests',table:'engineering_requests'},{label:'Projects',table:'engineering_projects'},{label:'Equipment',table:'engineering_equipment'},{label:'Support Tickets',table:'engineering_support_tickets'}],
  links:[{label:'Engineering Dashboard',href:'/engineering/dashboard',description:'Open engineering operations.'},{label:'Project Requests',href:'/engineering/request-project',description:'Review the engineering request workflow.'}]},
 host:{title:'Hosting Administration',desc:'Live hosting plans, orders, services and support operations.',action:'Manage Hosting',metrics:[
  {label:'Plans',table:'host_plans'},{label:'Orders',table:'host_orders'},{label:'Services',table:'host_services'},{label:'Support Tickets',table:'host_support_tickets'}],
  links:[{label:'Hosting Dashboard',href:'/host/dashboard',description:'Open hosting customer and service operations.'},{label:'Hosting Plans',href:'/host/plans',description:'Review live hosting plans.'},{label:'Domain Pricing',href:'/host/domains',description:'Review configured domain pricing.'}]},
 integrations:{title:'Integrations',desc:'Live visibility into provider connections, payment intents and notification delivery infrastructure.',action:'Review Integrations',metrics:[
  {label:'Provider Connections',table:'datasub_provider_connections'},{label:'Provider Events',table:'datasub_provider_events'},{label:'DataSub Payments',table:'datasub_payment_intents'},{label:'SchoolPro Payments',table:'schoolpro_payment_intents'}],
  links:[{label:'DataSub Providers',href:'/admin/datasub',description:'Review provider-backed DataSub operations.'},{label:'Notifications',href:'/admin/notifications',description:'Review templates, campaigns and deliveries.'},{label:'Security Centre',href:'/admin/security',description:'Review production security controls.'}]},
 finance:{title:'Finance',desc:'Live finance ledger, refund and platform payment activity.',action:'Review Finance',metrics:[
  {label:'Ledger Entries',table:'finance_ledger_entries'},{label:'Refund Requests',table:'finance_refund_requests'},{label:'School Fee Payments',table:'schoolpro_fee_payments'},{label:'Reseller Commissions',table:'datasub_reseller_commissions'}],
  links:[{label:'DataSub Transactions',href:'/admin/datasub',description:'Review DataSub financial operations.'},{label:'SchoolPro',href:'/admin/schoolpro',description:'Review SchoolPro finance operations.'}]},
 settings:{title:'System Settings',desc:'Production configuration and governance entry points for the IHLink platform.',action:'Review Settings',metrics:[
  {label:'Administrators',table:'admin_product_access'},{label:'Security Controls',table:'security_controls'},{label:'Readiness Checks',table:'launch_readiness_checks'},{label:'Content Blocks',table:'site_content_blocks'}],
  links:[{label:'Roles & Permissions',href:'/admin/roles',description:'Manage administrative access boundaries.'},{label:'Security Centre',href:'/admin/security',description:'Review security controls and incidents.'},{label:'Launch Readiness',href:'/admin/readiness',description:'Review production readiness checks.'},{label:'Website Builder',href:'/admin/content',description:'Manage database-backed website content.'}]}
};

export function AdminModulePage({module}:{module:string}){
 const {profile}=useAuth();
 const d=defs[module]||{title:module.replaceAll('-',' ').replace(/\b\w/g,x=>x.toUpperCase()),desc:'Production-backed administrative workspace.',action:'Production Control',metrics:[],links:[]};
 const [counts,setCounts]=useState<Record<string,number|null>>({}),[loading,setLoading]=useState(true),[error,setError]=useState<string|null>(null);
 const userName=profile?[profile.first_name,profile.last_name].filter(Boolean).join(' ')||profile.email:'Administrator';
 const load=async()=>{const client=supabase;if(!client){setError('Supabase is not configured.');setLoading(false);return;}setLoading(true);setError(null);
  const results=await Promise.all(d.metrics.map(async metric=>{let query=client.from(metric.table).select('*',{count:'exact',head:true});if(metric.filter)query=query.eq(metric.filter[0],metric.filter[1]);const {count,error}=await query;return{label:metric.label,count,error};}));
  const next:Record<string,number|null>={};for(const result of results){next[result.label]=result.count??0;if(result.error)setError(current=>current||result.error!.message);}setCounts(next);setLoading(false);};
 useEffect(()=>{void load();},[module]);
 const metrics=useMemo(()=>d.metrics.map(metric=>({label:metric.label,value:loading?'…':String(counts[metric.label]??0),change:undefined})),[d,counts,loading]);
 return <ModulePage product="corporate" sections={adminSections} title={d.title} eyebrow="Central Administration" description={d.desc} userName={userName} userRole={profile?.role?.replaceAll('_',' ')||'Authorized Administration'} primaryAction={d.action} metrics={metrics}>
  {error&&<div className="rounded-xl border border-amber-200 bg-amber-50 p-3 text-sm text-amber-800">Some live data could not be loaded: {error}</div>}
  <div className="grid gap-4 lg:grid-cols-[1.3fr_.7fr]">
   <Card padding="lg"><div className="flex items-start justify-between gap-3"><div><div className="flex items-center gap-2"><Database className="h-5 w-5 text-royal-600"/><h3 className="font-bold">Live production workspace</h3></div><p className="mt-2 text-sm text-muted">The figures above are queried from the production database. Zero means there is currently no matching production record; demonstration records are never substituted.</p></div><button onClick={()=>void load()} className="rounded-lg border p-2 text-muted hover:bg-gray-50" aria-label="Refresh live data"><RefreshCw className={`h-4 w-4 ${loading?'animate-spin':''}`}/></button></div>
    <div className="mt-5 grid gap-3 sm:grid-cols-2">{d.links.map(link=>{const schoolProDestination=link.href.startsWith('/schoolpro/');const content=<><div className="flex items-center justify-between gap-2"><span className="font-bold text-ink">{link.label}</span><ArrowRight className="h-4 w-4 text-muted transition group-hover:translate-x-0.5"/></div><p className="mt-1 text-xs leading-5 text-muted">{link.description}</p></>;return schoolProDestination?<button key={link.href} type="button" onClick={()=>void openPlatformWithHandoff('schoolpro',link.href)} className="group rounded-xl border border-border p-4 text-left transition hover:border-royal-200 hover:bg-royal-50/40">{content}</button>:<Link key={link.href} to={link.href} className="group rounded-xl border border-border p-4 transition hover:border-royal-200 hover:bg-royal-50/40">{content}</Link>})}</div>
   </Card>
   <Card padding="lg"><h3 className="font-bold">Data policy</h3><p className="mt-2 text-sm leading-6 text-muted">This control surface only displays live database-backed counts and routes to genuine operational pages. Customer, transaction, revenue, staff, incident and provider information is not fabricated when records do not exist.</p><div className="mt-4 rounded-xl bg-emerald-50 p-3 text-xs font-medium text-emerald-800">Production data mode active</div></Card>
  </div>
 </ModulePage>;
}
