import { useCallback, useEffect, useMemo, useState, type FormEvent } from "react";
import { Activity, CheckCircle2, ClipboardCheck, DatabaseBackup, ExternalLink, RefreshCw } from "lucide-react";
import { ModulePage } from "@/components/ModulePage";
import { Card } from "@/components/ui/Card";
import { Button } from "@/components/ui/Button";
import { useAuth } from "@/context/AuthContext";
import { supabase } from "@/lib/supabase";
import { adminSections, badge } from "./adminShared";

type Check={id:string;category:string;title:string;description:string;status:string;evidence:string|null;dashboard_url:string|null;verified_by:string|null;verified_at:string|null;updated_at:string};
type Drill={id:string;drill_number:number;drill_type:string;title:string;status:string;scope:string;evidence:string|null;scheduled_at:string;completed_at:string|null;created_at:string};
const field="w-full rounded-xl border border-border bg-white p-3 text-sm outline-none focus:border-royal-500";
const tone=(value:string):"green"|"amber"|"red"|"blue"=>["verified","passed"].includes(value)?"green":["blocked","failed"].includes(value)?"red":["pending","in_progress","scheduled"].includes(value)?"amber":"blue";

export function AdminReadinessPage(){
 const {user,profile}=useAuth();
 const [checks,setChecks]=useState<Check[]>([]),[drills,setDrills]=useState<Drill[]>([]),[notice,setNotice]=useState(""),[busy,setBusy]=useState(false);
 const [form,setForm]=useState({drill_type:"database_backup",title:"",scope:"",scheduled_at:""});
 const load=useCallback(async()=>{if(!supabase)return;const [c,d]=await Promise.all([
  supabase.from("launch_readiness_checks").select("id,category,title,description,status,evidence,dashboard_url,verified_by,verified_at,updated_at").order("sort_order"),
  supabase.from("recovery_drills").select("id,drill_number,drill_type,title,status,scope,evidence,scheduled_at,completed_at,created_at").order("scheduled_at",{ascending:false}).limit(50)
 ]);setChecks((c.data||[]) as Check[]);setDrills((d.data||[]) as Drill[]);setNotice(c.error?.message||d.error?.message||"");},[]);
 useEffect(()=>{void load();},[load]);
 const verified=useMemo(()=>checks.filter(x=>x.status==="verified").length,[checks]);
 const blocked=useMemo(()=>checks.filter(x=>x.status==="blocked").length,[checks]);
 const progress=checks.length?Math.round(verified/checks.length*100):0;
 async function audit(action:string,targetType:string,targetId:string){if(supabase&&user)await supabase.from("audit_logs").insert({actor_id:user.id,action,product:"corporate",target_type:targetType,target_id:targetId});}
 async function updateCheck(item:Check,status:string){if(!supabase||!user)return;setBusy(true);const evidence=status==="verified"?(window.prompt("Enter verification evidence. Do not mark this verified without proof.",item.evidence||"")||"").trim():item.evidence;if(status==="verified"&&!evidence){setNotice("Verification evidence is required.");setBusy(false);return;}const now=new Date().toISOString();const {error}=await supabase.from("launch_readiness_checks").update({status,evidence,verified_by:status==="verified"?user.id:null,verified_at:status==="verified"?now:null,updated_by:user.id,updated_at:now}).eq("id",item.id);if(error)setNotice(error.message);else{await audit(`Launch check ${item.title} marked ${status}`,"launch_readiness_check",item.id);setNotice("Readiness status updated.");await load();}setBusy(false);}
 async function createDrill(e:FormEvent){e.preventDefault();if(!supabase||!user)return;setBusy(true);const {data,error}=await supabase.from("recovery_drills").insert({...form,scheduled_at:new Date(form.scheduled_at).toISOString(),created_by:user.id,updated_by:user.id}).select("id").single();if(error)setNotice(error.message);else{await audit(`Recovery drill scheduled: ${form.title}`,"recovery_drill",data.id);setForm({drill_type:"database_backup",title:"",scope:"",scheduled_at:""});setNotice("Recovery drill scheduled.");await load();}setBusy(false);}
 async function updateDrill(item:Drill,status:string){if(!supabase||!user)return;setBusy(true);const evidence=["passed","failed"].includes(status)?(window.prompt("Record drill evidence, findings or recovery result.",item.evidence||"")||"").trim():item.evidence;if(["passed","failed"].includes(status)&&!evidence){setNotice("Completion evidence is required.");setBusy(false);return;}const {error}=await supabase.from("recovery_drills").update({status,evidence,completed_at:["passed","failed","cancelled"].includes(status)?new Date().toISOString():null,updated_by:user.id,updated_at:new Date().toISOString()}).eq("id",item.id);if(error)setNotice(error.message);else{await audit(`Recovery drill DR-${String(item.drill_number).padStart(4,"0")} marked ${status}`,"recovery_drill",item.id);setNotice("Recovery drill updated.");await load();}setBusy(false);}
 return <ModulePage product="corporate" sections={adminSections} title="Launch Readiness" description="Verify production dependencies, document evidence and test recovery before IHLink is opened to customers." userName={`${profile?.first_name||"IHLink"} ${profile?.last_name||"Administrator"}`} userRole={profile?.role==="super_admin"?"Super Administrator":"Company Administrator"} primaryAction="Production gate">
  <div className="grid gap-4 md:grid-cols-4"><Card><p className="text-sm text-muted">Launch readiness</p><p className="mt-2 text-3xl font-black text-royal-700">{progress}%</p></Card><Card><p className="text-sm text-muted">Verified controls</p><p className="mt-2 text-3xl font-black text-emerald-600">{verified}/{checks.length}</p></Card><Card><p className="text-sm text-muted">Blocked controls</p><p className="mt-2 text-3xl font-black text-rose-600">{blocked}</p></Card><Card><p className="text-sm text-muted">Recovery drills</p><p className="mt-2 text-3xl font-black text-sky-600">{drills.length}</p></Card></div>
  <Card><div className="flex flex-wrap items-center justify-between gap-3"><div><h3 className="font-bold">Production gate</h3><p className="mt-1 text-sm text-muted">The final launch approval must remain blocked until every critical requirement has current evidence.</p></div><Button size="sm" variant="secondary" leftIcon={<RefreshCw className="h-4 w-4"/>} onClick={()=>void load()}>Refresh</Button></div><div className="mt-4 h-3 overflow-hidden rounded-full bg-gray-100"><div className="h-full rounded-full bg-royal-600 transition-all" style={{width:`${progress}%`}}/></div></Card>
  {notice&&<div className="rounded-xl border border-royal-100 bg-royal-50 p-3 text-sm text-royal-900">{notice}</div>}
  <Card><div className="flex items-center gap-2"><ClipboardCheck className="h-5 w-5 text-royal-700"/><h3 className="font-bold">Launch verification checklist</h3></div><div className="mt-5 grid gap-4 lg:grid-cols-2">{checks.map(c=><div key={c.id} className="rounded-2xl border p-4"><div className="flex items-start justify-between gap-3"><div><p className="text-xs font-bold uppercase tracking-wide text-muted">{c.category}</p><h4 className="mt-1 font-bold">{c.title}</h4></div>{badge(c.status.replaceAll("_"," "),tone(c.status))}</div><p className="mt-2 text-sm text-muted">{c.description}</p>{c.evidence&&<p className="mt-3 rounded-xl bg-gray-50 p-3 text-xs text-muted"><strong>Evidence:</strong> {c.evidence}</p>}<div className="mt-3 flex flex-wrap items-center gap-2"><select aria-label={`Status for ${c.title}`} disabled={busy} className="rounded-lg border bg-white px-3 py-2 text-sm" value={c.status} onChange={e=>void updateCheck(c,e.target.value)}><option value="pending">Pending</option><option value="in_progress">In progress</option><option value="blocked">Blocked</option><option value="verified">Verified</option></select>{c.dashboard_url&&<a target="_blank" rel="noreferrer" className="inline-flex items-center gap-1 text-sm font-bold text-royal-700" href={c.dashboard_url}>Open setting <ExternalLink className="h-3.5 w-3.5"/></a>}</div></div>)}</div></Card>
  <div className="grid gap-6 xl:grid-cols-[.75fr_1.25fr]"><Card><div className="flex items-center gap-2"><DatabaseBackup className="h-5 w-5 text-sky-700"/><h3 className="font-bold">Schedule recovery drill</h3></div><p className="mt-2 text-sm text-muted">A dashboard status is not a backup. Schedule and record an actual recovery exercise.</p><form onSubmit={createDrill} className="mt-5 grid gap-4"><select className={field} value={form.drill_type} onChange={e=>setForm({...form,drill_type:e.target.value})}>{["database_backup","database_restore","data_export","account_recovery","incident_recovery"].map(x=><option key={x} value={x}>{x.replaceAll("_"," ")}</option>)}</select><input required className={field} placeholder="Drill title" value={form.title} onChange={e=>setForm({...form,title:e.target.value})}/><textarea required minLength={10} rows={4} className={field} placeholder="Systems, records and recovery objective covered" value={form.scope} onChange={e=>setForm({...form,scope:e.target.value})}/><input required aria-label="Scheduled date and time" type="datetime-local" className={field} value={form.scheduled_at} onChange={e=>setForm({...form,scheduled_at:e.target.value})}/><Button disabled={busy}>Schedule drill</Button></form></Card>
  <Card><div className="flex items-center gap-2"><Activity className="h-5 w-5 text-emerald-600"/><h3 className="font-bold">Recovery exercise register</h3></div><div className="mt-4 space-y-3">{drills.map(d=><div key={d.id} className="rounded-xl border p-4"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="font-bold">{d.title}</p><p className="mt-1 text-xs capitalize text-muted">DR-{String(d.drill_number).padStart(4,"0")} · {d.drill_type.replaceAll("_"," ")} · {new Date(d.scheduled_at).toLocaleString("en-NG")}</p></div>{badge(d.status.replaceAll("_"," "),tone(d.status))}</div><p className="mt-2 text-sm text-muted">{d.scope}</p>{d.evidence&&<p className="mt-2 text-xs text-muted"><strong>Result:</strong> {d.evidence}</p>}<div className="mt-3"><select aria-label={`Status for drill ${d.drill_number}`} disabled={busy} className="rounded-lg border bg-white px-3 py-2 text-sm" value={d.status} onChange={e=>void updateDrill(d,e.target.value)}><option value="scheduled">Scheduled</option><option value="in_progress">In progress</option><option value="passed">Passed</option><option value="failed">Failed</option><option value="cancelled">Cancelled</option></select></div></div>)}{!drills.length&&<div className="py-10 text-center"><CheckCircle2 className="mx-auto h-8 w-8 text-muted"/><p className="mt-2 text-sm text-muted">No recovery drills scheduled yet.</p></div>}</div></Card></div>
 </ModulePage>;
}
