import {useEffect,useState} from 'react';
import {ModulePage} from '@/components/ModulePage';
import {Card} from '@/components/ui/Card';
import {Button} from '@/components/ui/Button';
import {adminSections} from './adminShared';
import {supabase} from '@/lib/supabase';
import {useAuth} from '@/context/AuthContext';
import {naira} from '@/lib/designTokens';
type Invite={referred_user_id:string;referrer_user_id:string;created_at:string};
export function AdminDataSubReferrals(){const {profile,user}=useAuth();const [enabled,setEnabled]=useState(false),[reward,setReward]=useState('0'),[minimum,setMinimum]=useState('0'),[reason,setReason]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false),[invites,setInvites]=useState<Invite[]>([]),[approved,setApproved]=useState<string[]>([]),[selected,setSelected]=useState(''),[transaction,setTransaction]=useState('');
 async function load(){if(!supabase)return;const [p,i,r]=await Promise.all([supabase.from('datasub_referral_program').select('enabled,reward_amount,minimum_purchase').eq('id',true).single(),supabase.from('datasub_referral_invitees').select('referred_user_id,referrer_user_id,created_at').order('created_at',{ascending:false}).limit(500),supabase.from('datasub_referral_rewards').select('referred_user_id').limit(1000)]);if(p.error||i.error||r.error){setNotice('Referral programme could not be loaded.');return;}setEnabled(p.data.enabled);setReward(String(p.data.reward_amount));setMinimum(String(p.data.minimum_purchase));setInvites(i.data||[]);setApproved((r.data||[]).map(x=>x.referred_user_id));}
 useEffect(()=>{void load();},[]);
 async function save(){if(!supabase||reason.trim().length<3){setNotice('Enter an audit reason.');return;}setBusy(true);const r=await supabase.rpc('configure_datasub_referrals',{p_enabled:enabled,p_reward:Number(reward),p_minimum:Number(minimum),p_reason:reason.trim()});setNotice(r.error?r.error.message:'Referral terms saved.');setBusy(false);}
 async function approve(){if(!supabase||!selected||!transaction||reason.trim().length<3){setNotice('Select an invitee and enter a verified purchase ID and audit reason.');return;}setBusy(true);const r=await supabase.rpc('approve_datasub_referral_reward',{p_referred:selected,p_transaction:transaction.trim(),p_reason:reason.trim()});setNotice(r.error?r.error.message:`Reward approved: ${naira(Number(r.data?.amount||0))}`);setBusy(false);if(!r.error)await load();}
 const field='mt-2 w-full rounded-xl border p-3';return <ModulePage product="datasub" sections={adminSections} title="DataSub Referral Programme" description="Configure rewards and verify qualifying purchases before awarding earnings." userName={profile?.first_name||'Super Administrator'} userRole="Super Administrator"><Card><h2 className="font-bold">Programme terms</h2><p className="mt-2 text-sm text-muted">Rewards start disabled. Approval requires a successful purchase after the invitation, the minimum purchase amount and enough recorded profit to cover the reward. Each invited account earns one reward. Later refunds and suspected abuse require finance review; approved promotional rewards are not automatically clawed back.</p><div className="mt-4 grid gap-4 sm:grid-cols-2"><label className="text-sm font-bold">Reward (₦)<input type="number" min="0" step="0.01" className={field} value={reward} onChange={e=>setReward(e.target.value)}/></label><label className="text-sm font-bold">Minimum qualifying purchase (₦)<input type="number" min="0" step="0.01" className={field} value={minimum} onChange={e=>setMinimum(e.target.value)}/></label></div><label className="mt-4 flex min-h-11 items-center gap-3"><input type="checkbox" checked={enabled} onChange={e=>setEnabled(e.target.checked)}/>Enable verified referral rewards</label><label className="mt-4 block text-sm font-bold">Audit / verification reason<textarea value={reason} onChange={e=>setReason(e.target.value)} className={field}/></label><Button disabled={busy} className="mt-4" onClick={()=>void save()}>Save terms</Button></Card><Card className="mt-5"><h2 className="font-bold">Verify and approve a reward</h2><label className="mt-4 block text-sm font-bold">Invitee<select className={field} value={selected} onChange={e=>setSelected(e.target.value)}><option value="">Choose an unawarded invitation</option>{invites.filter(x=>!approved.includes(x.referred_user_id)).map(x=><option key={x.referred_user_id} value={x.referred_user_id}>{x.referred_user_id} · {new Date(x.created_at).toLocaleDateString()}</option>)}</select></label><label className="mt-4 block text-sm font-bold">Successful DataSub transaction ID<input value={transaction} onChange={e=>setTransaction(e.target.value)} className={field}/></label><Button disabled={busy||!enabled} className="mt-4" onClick={()=>void approve()}>Verify purchase & approve reward</Button><p className="mt-3 text-sm text-muted">{invites.length} invitations · {approved.length} approved rewards</p></Card>{notice&&<p role="status" className="mt-4 rounded-xl border p-3 text-sm">{notice}</p>}</ModulePage>;}
