import {useCallback,useEffect,useState} from 'react';
import {Link} from 'react-router-dom';
import {RefreshCw,School} from 'lucide-react';
import {ModulePage} from '@/components/ModulePage';
import {Card} from '@/components/ui/Card';
import {Button} from '@/components/ui/Button';
import {supabase} from '@/lib/supabase';
import {useAuth} from '@/context/AuthContext';
import {adminSections,badge} from './adminShared';
type Request={id:string;user_id:string|null;school_name:string;contact_name:string;email:string;phone:string|null;student_count:number|null;modules:string[];status:string;school_id:string|null;created_at:string;review_notes:string|null};
type Plan={code:string;name:string};
export function AdminSchoolProOnboarding(){
 const {profile}=useAuth();const [rows,setRows]=useState<Request[]>([]),[plans,setPlans]=useState<Plan[]>([]),[query,setQuery]=useState(''),[filter,setFilter]=useState('all'),[loading,setLoading]=useState(true),[message,setMessage]=useState('');
 const load=useCallback(async()=>{if(!supabase)return;setLoading(true);try{const [a,b]=await Promise.all([supabase.from('schoolpro_onboarding_requests').select('id,user_id,school_name,contact_name,email,phone,student_count,modules,status,school_id,created_at,review_notes').order('created_at',{ascending:false}).limit(500),supabase.from('schoolpro_subscription_catalog').select('code,name').eq('active',true)]);if(a.error||b.error)throw a.error||b.error;setRows(a.data||[]);setPlans(b.data||[]);}catch{setMessage('School requests could not be loaded. Please refresh.');}finally{setLoading(false);}},[]);
 useEffect(()=>{void load();const refresh=()=>{if(document.visibilityState==='visible')void load();};const timer=window.setInterval(refresh,30000);window.addEventListener('focus',refresh);return()=>{window.clearInterval(timer);window.removeEventListener('focus',refresh);};},[load]);
 const visible=rows.filter(r=>(filter==='all'||r.status===filter)&&[r.school_name,r.contact_name,r.email,r.id].join(' ').toLowerCase().includes(query.toLowerCase()));
 return <ModulePage product="corporate" sections={adminSections} title="School registration requests" description="Review submissions from the SchoolPro app and browser, create the school workspace and manage activation." userName={profile?.email||'IHLink'} userRole="Super Administrator" metrics={[{label:'Requests',value:String(rows.length)},{label:'Awaiting review',value:String(rows.filter(r=>['submitted','reviewing'].includes(r.status)).length)},{label:'Activation pending',value:String(rows.filter(r=>['approved','provisioning'].includes(r.status)).length)},{label:'Active',value:String(rows.filter(r=>r.status==='active').length)}]}>
 <Card><div className="flex flex-wrap gap-3"><input aria-label="Search school requests" className="min-w-0 flex-1 rounded-xl border p-3" placeholder="Search school, contact, email or reference" value={query} onChange={e=>setQuery(e.target.value)}/><select aria-label="Request status" className="rounded-xl border p-3" value={filter} onChange={e=>setFilter(e.target.value)}>{['all','submitted','reviewing','approved','provisioning','active','rejected'].map(s=><option key={s} value={s}>{s}</option>)}</select><Button variant="secondary" disabled={loading} onClick={()=>void load()} leftIcon={<RefreshCw size={18}/>}>Refresh</Button></div>{message&&<p role="status" className="mt-3 text-sm">{message}</p>}</Card>
 {loading&&<p role="status">Loading school requests…</p>}{!loading&&!visible.length&&<Card>No requests match your filter.</Card>}
 <div className="grid gap-4">{visible.map(row=><RequestCard key={row.id} row={row} plans={plans} reload={load} report={setMessage}/>)}</div>
 </ModulePage>;
}
function RequestCard({row,plans,reload,report}:{row:Request;plans:Plan[];reload:()=>Promise<void>;report:(v:string)=>void}){
 const [note,setNote]=useState(''),[tier,setTier]=useState('starter'),[busy,setBusy]=useState(false);
 async function act(action:string){if(!supabase||busy)return;if(note.trim().length<3){report('Enter a review or activation reason.');return;}setBusy(true);try{const {error}=await supabase.rpc('review_schoolpro_onboarding',{p_request:row.id,p_action:action,p_expected_status:row.status,p_note:note.trim(),p_tier:tier});if(error){report(error.message);return;}report(action==='activate'?'Workspace activated through the authorized control-center override. No payment was recorded.':'School request updated.');await reload();}catch{report('This action could not be completed. Refresh and try again.');}finally{setBusy(false);}}
 return <Card><div className="flex flex-wrap items-start justify-between gap-3"><div><h2 className="flex items-center gap-2 text-lg font-bold"><School size={22}/>{row.school_name.trim()}</h2><p className="mt-1 text-sm">{row.contact_name} · {row.email}</p><p className="text-sm text-muted">{row.phone||'No phone'} · {row.student_count??'Not specified'} students</p><p className="mt-2 break-all text-xs text-muted">Request {row.id} · {new Date(row.created_at).toLocaleString()}</p></div>{badge(row.status,row.status==='active'?'green':row.status==='rejected'?'red':'amber')}</div><p className="mt-3 text-sm">Modules: {(row.modules||[]).join(', ')||'Not selected'}</p>
 {row.school_id&&<Link className="mt-3 inline-block font-semibold text-royal-600" to={`/admin/schoolpro/workspace/overview?school_id=${row.school_id}`}>Open linked school</Link>}
 {row.status!=='active'&&<div className="mt-4 space-y-3"><label className="block text-sm font-semibold">Review / activation reason<textarea className="mt-1 w-full rounded-xl border p-3 font-normal" value={note} onChange={e=>setNote(e.target.value)} placeholder="Record why you are taking this action"/></label><div className="flex flex-wrap gap-2">
 {!row.school_id&&<>{row.status!=='reviewing'&&<Button variant="secondary" disabled={busy} onClick={()=>void act('review')}>Review</Button>}{['submitted','reviewing'].includes(row.status)&&<><Button disabled={busy} onClick={()=>void act('approve')}>Approve request</Button><Button variant="danger" disabled={busy} onClick={()=>void act('reject')}>Reject request</Button></>}</>}
 {['approved','provisioning'].includes(row.status)&&<>{!row.school_id&&<Button disabled={busy||!row.user_id} onClick={()=>void act('provision')}>Create school workspace</Button>}<select aria-label="Activation plan" className="rounded-xl border p-3" value={tier} onChange={e=>setTier(e.target.value)}>{plans.map(p=><option key={p.code} value={p.code}>{p.name}</option>)}</select><Button variant="secondary" disabled={busy||!row.user_id||!plans.some(p=>p.code===tier)} onClick={()=>void act('activate')}>Activate by authorized override</Button></>}
 </div>{!row.user_id&&<p className="text-sm text-amber-700">The proprietor must activate their account before this request can be provisioned.</p>}<p className="text-xs text-muted">Workspace creation does not activate a paid subscription. An activation override grants access without marking an invoice or payment as paid.</p></div>}
 </Card>;
}
