import { BarChart3, Bell, Building2, ClipboardCheck, Cpu, CreditCard, FileText, GraduationCap, Headphones, LayoutDashboard, LockKeyhole, Plug, Server, Settings, ShieldCheck, Smartphone, UserCog, Users, Wrench } from 'lucide-react'; import type { SidebarSection } from '@/components/Sidebar';
import { platformUrl } from '@/lib/platformUrls';
export const adminSections:SidebarSection[]=[
 {items:[{label:'Command Centre',href:'/admin',icon:<LayoutDashboard className="w-4 h-4"/>},{label:'Corporate Site',href:platformUrl('corporate'),icon:<Building2 className="w-4 h-4"/>},{label:'Customer Dashboard',href:platformUrl('corporate','/account'),icon:<Smartphone className="w-4 h-4"/>},{label:'Products',href:'/admin/products',icon:<BarChart3 className="w-4 h-4"/>},{label:'Base Pricing',href:'/admin/pricing',icon:<CreditCard className="w-4 h-4"/>}]},
 {title:'Platforms',items:[{label:'Website Builder',href:'/admin/content',icon:<Building2 className="w-4 h-4"/>},{label:'DataSub',href:'/admin/datasub',icon:<Smartphone className="w-4 h-4"/>},{label:'DataSub Provider Pricing',href:'/admin/datasub/provider-pricing',icon:<CreditCard className="w-4 h-4"/>},{label:'SchoolPro',href:'/admin/schoolpro',icon:<GraduationCap className="w-4 h-4"/>},{label:'Consult',href:'/admin/consult',icon:<Wrench className="w-4 h-4"/>},{label:'Host',href:'/admin/host',icon:<Server className="w-4 h-4"/>},{label:'Engineering',href:'/admin/engineering',icon:<Cpu className="w-4 h-4"/>},{label:'Business & Innovation',href:'/admin/business-centre',icon:<Building2 className="w-4 h-4"/>},{label:'Print & Branding',href:'/admin/print',icon:<FileText className="w-4 h-4"/>},{label:'3D & Fabrication',href:'/admin/fabrication',icon:<Wrench className="w-4 h-4"/>},{label:'AI & Compute',href:'/admin/compute',icon:<Cpu className="w-4 h-4"/>},{label:'Academy',href:'/admin/academy',icon:<GraduationCap className="w-4 h-4"/>},{label:'Digital Business',href:'/admin/digital-business',icon:<Smartphone className="w-4 h-4"/>}]},
 {title:'Management',items:[{label:'Customers',href:'/admin/customers',icon:<Users className="w-4 h-4"/>},{label:'Administrators',href:'/admin/administrators',icon:<UserCog className="w-4 h-4"/>},{label:'Roles & Permissions',href:'/admin/roles',icon:<ShieldCheck className="w-4 h-4"/>},{label:'Finance',href:'/admin/finance',icon:<CreditCard className="w-4 h-4"/>},{label:'Support',href:'/admin/support',icon:<Headphones className="w-4 h-4"/>}]},
 {title:'System',items:[{label:'Notifications',href:'/admin/notifications',icon:<Bell className="w-4 h-4"/>},{label:'Security Centre',href:'/admin/security',icon:<LockKeyhole className="w-4 h-4"/>},{label:'Launch Readiness',href:'/admin/readiness',icon:<ClipboardCheck className="w-4 h-4"/>},{label:'Audit Logs',href:'/admin/audit-logs',icon:<FileText className="w-4 h-4"/>},{label:'Integrations',href:'/admin/integrations',icon:<Plug className="w-4 h-4"/>},{label:'Settings',href:'/admin/settings',icon:<Settings className="w-4 h-4"/>}]}
];
export const badge=(label:string,tone:'green'|'amber'|'red'|'blue'='green')=>{const c={green:'bg-emerald-50 text-emerald-700',amber:'bg-amber-50 text-amber-700',red:'bg-rose-50 text-rose-700',blue:'bg-sky-50 text-sky-700'}[tone];return <span className={`rounded-full px-2.5 py-1 text-xs font-bold ${c}`}>{label}</span>}
