import { useEffect, useMemo, useState } from 'react';
import { Link } from 'react-router-dom';
import { Activity, Building2, Cpu, ExternalLink, Globe2, GraduationCap, Headphones, Server, ShieldCheck, Smartphone, Users, Wrench } from 'lucide-react';
import { ModulePage } from '@/components/ModulePage';
import { Card } from '@/components/ui/Card';
import { Button } from '@/components/ui/Button';
import { adminSections, badge } from './adminShared';
import { supabase } from '@/lib/supabase';
import { useAuth } from '@/context/AuthContext';
import { platformUrl, type PlatformKey } from '@/lib/platformUrls';

type Counts={users:number;schools:number;products:number;transactions:number;consult:number;engineering:number;hostOrders:number;hostServices:number;businessOrders:number;businessServices:number;printOrders:number;fabricationJobs:number;computeJobs:number;academy:number;tickets:number;security:number};
const initial:Counts={users:0,schools:0,products:0,transactions:0,consult:0,engineering:0,hostOrders:0,hostServices:0,businessOrders:0,businessServices:0,printOrders:0,fabricationJobs:0,computeJobs:0,academy:0,tickets:0,security:0};
const platforms=[
 {name:'Corporate',key:'corporate',href:'/',admin:'/admin/content',icon:Building2,description:'Parent company, shared content and customer entry point.'},
 {name:'DataSub',key:'datasub',href:'/datasub',admin:'/admin/datasub',icon:Smartphone,description:'VTU catalog, wallets, transactions, reseller and developer API.'},
 {name:'SchoolPro',key:'schoolpro',href:'/schoolpro',admin:'/admin/schoolpro',icon:GraduationCap,description:'Schools, academics, results, fees, parents and staff.'},
 {name:'Consult',key:'consult',href:'/consult',admin:'/admin/consult',icon:Wrench,description:'Enquiries, quotations, projects and client delivery.'},
 {name:'Engineering',key:'engineering',href:'/engineering',admin:'/admin/engineering',icon:Cpu,description:'Engineering requests, projects, field work and support.'},
 {name:'Hosting',key:'host',href:'/host',admin:'/admin/host',icon:Server,description:'Domains, hosting catalog, orders, services and tickets.'},
 {name:'Business & Innovation Centre',key:'business_centre',href:'/business-centre',admin:'/admin/business-centre',icon:Building2,description:'Unified business, production and innovation operations.'},
 {name:'Print & Branding',key:'print',href:'/print',admin:'/admin/print',icon:Wrench,description:'Print, branding, signage and production orders.'},
 {name:'3D & Fabrication Lab',key:'fabrication',href:'/fabrication',admin:'/admin/fabrication',icon:Wrench,description:'CAD, prototyping and fabrication workflows.'},
 {name:'AI & Compute',key:'compute',href:'/compute',admin:'/admin/compute',icon:Cpu,description:'AI, data and compute workloads.'},
 {name:'IHLink Academy',key:'academy',href:'/academy',admin:'/admin/academy',icon:GraduationCap,description:'Courses, enrolments and training operations.'},
 {name:'Digital Business Centre',key:'digital_business',href:'/business-centre/digital-services',admin:'/admin/digital-business',icon:Smartphone,description:'Digital document and business service requests.'},
] as const;
async function count(table:string){if(!supabase)throw new Error('Supabase is not configured.');const r=await supabase.from(table).select('*',{count:'exact',head:true});if(r.error)throw new Error(`${table}: ${r.error.message}`);return r.count??0;}
export function AdminDashboard(){
 const {profile,adminAccess}=useAuth();const [counts,setCounts]=useState(initial);const [loading,setLoading]=useState(true);const [error,setError]=useState('');
 useEffect(()=>{if(!supabase){setError('Supabase is not configured.');setLoading(false);return;}void(async()=>{setLoading(true);const vals=await Promise.all(['profiles','schoolpro_schools','datasub_products','datasub_transactions','consult_projects','engineering_projects','host_orders','host_services','business_orders','business_catalog','print_orders','fabrication_jobs','compute_jobs','academy_enrollments','support_tickets','security_events'].map(count));setCounts({users:vals[0],schools:vals[1],products:vals[2],transactions:vals[3],consult:vals[4],engineering:vals[5],hostOrders:vals[6],hostServices:vals[7],businessOrders:vals[8],businessServices:vals[9],printOrders:vals[10],fabricationJobs:vals[11],computeJobs:vals[12],academy:vals[13],tickets:vals[14],security:vals[15]});setLoading(false);})().catch(e=>{setError(e instanceof Error?e.message:'Unable to load command centre.');setLoading(false);});},[]);
 const platformMeta=useMemo(()=>({corporate:`${counts.users} profiles`,datasub:`${counts.products} catalog products · ${counts.transactions} transactions`,schoolpro:`${counts.schools} schools`,consult:`${counts.consult} projects`,engineering:`${counts.engineering} projects`,host:`${counts.hostOrders} orders · ${counts.hostServices} active services`,business_centre:`${counts.businessOrders} orders · ${counts.businessServices} services`,print:`${counts.printOrders} print orders`,fabrication:`${counts.fabricationJobs} fabrication jobs`,compute:`${counts.computeJobs} compute jobs`,academy:`${counts.academy} enrolments`,digital_business:`${counts.businessOrders} business-centre orders`}),[counts]);
 const visiblePlatforms=profile?.role==="super_admin"?platforms:platforms.filter(p=>adminAccess.some(a=>a.product===p.key&&a.can_use_command_center));
 const name=[profile?.first_name,profile?.middle_name,profile?.last_name].filter(Boolean).join(' ')||profile?.email||'Administrator';
 return <ModulePage product="corporate" sections={adminSections} title="IHLink Control Centre" eyebrow={profile?.role==="super_admin"?"Central Super Administration":"Assigned Platform Administration"} description="One secure operational workspace for the corporate site and the complete IHLink ecosystem, including every Business & Innovation unit. Data shown here is read from the production database, not demonstration metrics." userName={name} userRole={profile?.role==='super_admin'?'Super Administrator':'Platform Administrator'} primaryAction="Production Control" metrics={[{label:'Customer Profiles',value:loading?'—':String(counts.users)},{label:'DataSub Products',value:loading?'—':String(counts.products)},{label:'Registered Schools',value:loading?'—':String(counts.schools)},{label:'Open Support Tickets',value:loading?'—':String(counts.tickets)}]}>
 {error&&<div className="rounded-xl border border-rose-200 bg-rose-50 p-4 text-sm text-rose-700">{error}</div>}
 <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{visiblePlatforms.map(p=>{const Icon=p.icon;return <Card key={p.key} hover><div className="flex items-start justify-between"><div className="grid h-11 w-11 place-items-center rounded-xl bg-navy-800 text-white"><Icon className="h-5 w-5"/></div></div><h3 className="mt-4 text-lg font-extrabold">{p.name}</h3><p className="mt-1 text-sm text-muted">{p.description}</p><p className="mt-4 text-sm font-semibold">{platformMeta[p.key]}</p><div className="mt-5 flex gap-2"><Link to={p.admin}><Button size="sm">Manage</Button></Link><a href={platformUrl(p.key as PlatformKey,p.href)}><Button size="sm" variant="secondary" rightIcon={<ExternalLink className="h-3.5 w-3.5"/>}>Open site</Button></a></div></Card>})}</div>
 <div className="grid gap-5 lg:grid-cols-3"><Card><div className="flex gap-3"><ShieldCheck className="h-6 w-6 text-emerald-600"/><div><h3 className="font-bold">Access & Security</h3><p className="mt-1 text-sm text-muted">Role-protected administration, RLS-backed data access and centralized security operations.</p><Link to="/admin/security"><Button size="sm" variant="secondary" className="mt-4">Security Centre</Button></Link></div></div></Card><Card><div className="flex gap-3"><Headphones className="h-6 w-6 text-royal-600"/><div><h3 className="font-bold">Unified Support</h3><p className="mt-1 text-sm text-muted">{counts.tickets} central support tickets currently recorded.</p><Link to="/admin/support"><Button size="sm" variant="secondary" className="mt-4">Support Operations</Button></Link></div></div></Card><Card><div className="flex gap-3"><Activity className="h-6 w-6 text-amber-600"/><div><h3 className="font-bold">Security Events</h3><p className="mt-1 text-sm text-muted">{counts.security} security events currently recorded.</p><Link to="/admin/readiness"><Button size="sm" variant="secondary" className="mt-4">Launch Readiness</Button></Link></div></div></Card></div>
 <Card><div className="flex flex-col gap-4 lg:flex-row lg:items-center lg:justify-between"><div><div className="flex items-center gap-2"><Globe2 className="h-5 w-5 text-royal-600"/><h3 className="font-bold">Independent-domain architecture</h3></div><p className="mt-2 max-w-3xl text-sm text-muted">Corporate, DataSub, SchoolPro, Consult, Engineering, Hosting and this Admin Control Centre are prepared to run as independent Vercel projects while sharing one Supabase identity and authorization layer.</p></div><Link to="/admin/readiness"><Button>Review deployment readiness</Button></Link></div></Card>
 </ModulePage>
}
