import { useCallback, useEffect, useMemo, useState, type FormEvent } from "react";
import { AlertTriangle, CheckCircle2, FileWarning, RefreshCw, ShieldCheck } from "lucide-react";
import { ModulePage } from "@/components/ModulePage";
import { Card } from "@/components/ui/Card";
import { Button } from "@/components/ui/Button";
import { useAuth } from "@/context/AuthContext";
import { supabase } from "@/lib/supabase";
import { adminSections, badge } from "./adminShared";

type Control={id:string;category:string;title:string;description:string;status:string;guidance:string|null;dashboard_url:string|null;updated_at:string};
type Event={id:string;event_number:string;event_type:string;severity:string;title:string;description:string|null;product:string;status:string;actor_id:string|null;created_at:string};
type Incident={id:string;incident_number:string;event_id:string|null;title:string;severity:string;status:string;product:string;summary:string;resolution:string|null;assigned_to:string|null;created_at:string};
type Audit={id:number;actor_id:string|null;action:string;product:string|null;target_type:string|null;created_at:string};
type Person={id:string;email:string;first_name:string|null;last_name:string|null;role:string};
const field="w-full rounded-xl border border-border bg-white p-3 text-sm outline-none focus:border-royal-500";
const products=["corporate","datasub","schoolpro","consult","host","engineering","business_centre","print","fabrication","compute","academy","digital_business","system"];
const fullName=(p?:Person)=>p?[p.first_name,p.last_name].filter(Boolean).join(" ")||p.email:"System";
const tone=(value:string):"green"|"amber"|"red"|"blue"=>["enabled","verified","resolved","closed"].includes(value)?"green":["high","critical","blocked"].includes(value)?"red":["medium","action_required","open","investigating","reviewing"].includes(value)?"amber":"blue";

export function AdminSecurityPage(){
 const {user,profile}=useAuth();
 const [controls,setControls]=useState<Control[]>([]),[events,setEvents]=useState<Event[]>([]),[incidents,setIncidents]=useState<Incident[]>([]),[logs,setLogs]=useState<Audit[]>([]),[people,setPeople]=useState<Person[]>([]),[notice,setNotice]=useState(""),[busy,setBusy]=useState(false);
 const [form,setForm]=useState({event_type:"manual_report",severity:"medium",product:"corporate",title:"",description:""});
 const load=useCallback(async()=>{if(!supabase)return;const [c,e,i,a,p]=await Promise.all([
  supabase.from("security_controls").select("id,category,title,description,status,guidance,dashboard_url,updated_at").order("category"),
  supabase.from("security_events").select("id,event_number,event_type,severity,title,description,product,status,actor_id,created_at").order("created_at",{ascending:false}).limit(100),
  supabase.from("security_incidents").select("id,incident_number,event_id,title,severity,status,product,summary,resolution,assigned_to,created_at").order("created_at",{ascending:false}).limit(100),
  supabase.from("audit_logs").select("id,actor_id,action,product,target_type,created_at").order("created_at",{ascending:false}).limit(30),
  supabase.from("profiles").select("id,email,first_name,last_name,role").neq("role","customer").eq("status","active")
 ]);setControls((c.data||[]) as Control[]);setEvents((e.data||[]) as Event[]);setIncidents((i.data||[]) as Incident[]);setLogs((a.data||[]) as Audit[]);setPeople((p.data||[]) as Person[]);setNotice(c.error?.message||e.error?.message||i.error?.message||a.error?.message||p.error?.message||"");},[]);
 useEffect(()=>{void load();},[load]);
 const openEvents=useMemo(()=>events.filter(x=>["open","reviewing"].includes(x.status)),[events]);
 const openIncidents=useMemo(()=>incidents.filter(x=>!["resolved","closed"].includes(x.status)),[incidents]);
 async function audit(action:string,targetType:string,targetId:string){if(supabase&&user)await supabase.from("audit_logs").insert({actor_id:user.id,action,product:"corporate",target_type:targetType,target_id:targetId});}
 async function createEvent(e:FormEvent){e.preventDefault();if(!supabase||!user)return;setBusy(true);const {data,error}=await supabase.from("security_events").insert({...form,actor_id:user.id,source:"ihlink_admin"}).select("id").single();if(error)setNotice(error.message);else{await audit(`Security event recorded: ${form.title}`,"security_event",data.id);setNotice("Security event recorded.");setForm({event_type:"manual_report",severity:"medium",product:"corporate",title:"",description:""});await load();}setBusy(false);}
 async function updateEvent(item:Event,status:string){if(!supabase||!user)return;setBusy(true);const {error}=await supabase.from("security_events").update({status,reviewed_by:user.id,reviewed_at:new Date().toISOString(),updated_at:new Date().toISOString()}).eq("id",item.id);if(error)setNotice(error.message);else{await audit(`Security event ${item.event_number} marked ${status}`,"security_event",item.id);await load();}setBusy(false);}
 async function createIncident(item:Event){if(!supabase||!user)return;setBusy(true);const {data,error}=await supabase.from("security_incidents").insert({event_id:item.id,title:item.title,severity:item.severity==="info"?"low":item.severity,product:item.product,summary:item.description||`Investigation opened from ${item.event_number}.`,created_by:user.id,assigned_to:user.id}).select("id").single();if(error)setNotice(error.message);else{await updateEvent(item,"reviewing");await audit(`Incident opened from ${item.event_number}`,"security_incident",data.id);setNotice("Incident opened and assigned for investigation.");await load();}setBusy(false);}
 async function updateIncident(item:Incident,status:string){if(!supabase||!user)return;setBusy(true);const payload={status,updated_at:new Date().toISOString(),resolved_at:["resolved","closed"].includes(status)?new Date().toISOString():null};const {error}=await supabase.from("security_incidents").update(payload).eq("id",item.id);if(error)setNotice(error.message);else{await audit(`Security incident ${item.incident_number} marked ${status}`,"security_incident",item.id);await load();}setBusy(false);}
 async function updateControl(item:Control,status:string){if(!supabase||!user)return;setBusy(true);const {error}=await supabase.from("security_controls").update({status,updated_by:user.id,updated_at:new Date().toISOString()}).eq("id",item.id);if(error)setNotice(error.message);else{await audit(`Security control ${item.title} marked ${status}`,"security_control",item.id);await load();}setBusy(false);}
 const personMap=new Map(people.map(x=>[x.id,x]));
 return <ModulePage product="corporate" sections={adminSections} title="Security Centre" description="Monitor IHLink security controls, review operational events and manage incidents without exposing customer data." userName={`${profile?.first_name||"IHLink"} ${profile?.last_name||"Administrator"}`} userRole={profile?.role==="super_admin"?"Super Administrator":"Company Administrator"} primaryAction="Security review">
  <div className="grid gap-4 md:grid-cols-4"><Card><p className="text-sm text-muted">Controls enabled</p><p className="mt-2 text-3xl font-black text-emerald-600">{controls.filter(x=>x.status==="enabled").length}/{controls.length}</p></Card><Card><p className="text-sm text-muted">Open events</p><p className="mt-2 text-3xl font-black text-amber-600">{openEvents.length}</p></Card><Card><p className="text-sm text-muted">Open incidents</p><p className="mt-2 text-3xl font-black text-rose-600">{openIncidents.length}</p></Card><Card><p className="text-sm text-muted">Administrators monitored</p><p className="mt-2 text-3xl font-black text-royal-600">{people.length}</p></Card></div>
  {notice&&<div className="rounded-xl border border-royal-100 bg-royal-50 p-3 text-sm text-royal-900">{notice}</div>}
  <Card><div className="flex flex-wrap items-center justify-between gap-3"><div><h3 className="font-bold">Production security controls</h3><p className="mt-1 text-sm text-muted">Status is tracked here; provider-level settings still require verification in their dashboards.</p></div><Button size="sm" variant="secondary" leftIcon={<RefreshCw className="h-4 w-4"/>} onClick={()=>void load()}>Refresh</Button></div><div className="mt-5 grid gap-4 lg:grid-cols-2">{controls.map(c=><div key={c.id} className="rounded-2xl border p-4"><div className="flex items-start justify-between gap-3"><div><p className="text-xs font-bold uppercase tracking-wide text-muted">{c.category}</p><h4 className="mt-1 font-bold">{c.title}</h4></div>{badge(c.status.replaceAll('_',' '),tone(c.status))}</div><p className="mt-2 text-sm text-muted">{c.description}</p>{c.guidance&&<p className="mt-3 rounded-xl bg-gray-50 p-3 text-xs text-muted">{c.guidance}</p>}<div className="mt-3 flex flex-wrap items-center gap-2"><select aria-label={`Status for ${c.title}`} disabled={busy} className="rounded-lg border bg-white px-3 py-2 text-sm" value={c.status} onChange={e=>void updateControl(c,e.target.value)}><option value="enabled">Enabled</option><option value="action_required">Action required</option><option value="planned">Planned</option><option value="manual_review">Manual review</option></select>{c.dashboard_url&&<a target="_blank" rel="noreferrer" className="text-sm font-bold text-royal-700" href={c.dashboard_url}>Open provider setting</a>}</div></div>)}</div></Card>
  <div className="grid gap-6 xl:grid-cols-[.8fr_1.2fr]"><Card><div className="flex items-center gap-2"><FileWarning className="h-5 w-5 text-amber-600"/><h3 className="font-bold">Record security event</h3></div><p className="mt-2 text-sm text-muted">For suspicious access, provider warnings or issues found during operational review.</p><form onSubmit={createEvent} className="mt-5 grid gap-4"><div className="grid gap-4 md:grid-cols-2"><select className={field} value={form.event_type} onChange={e=>setForm({...form,event_type:e.target.value})}>{["authentication","permission_change","account_change","data_access","financial_action","provider_event","manual_report","system"].map(x=><option key={x} value={x}>{x.replaceAll('_',' ')}</option>)}</select><select className={field} value={form.severity} onChange={e=>setForm({...form,severity:e.target.value})}>{["info","low","medium","high","critical"].map(x=><option key={x}>{x}</option>)}</select></div><select className={field} value={form.product} onChange={e=>setForm({...form,product:e.target.value})}>{products.map(x=><option key={x}>{x}</option>)}</select><input required className={field} placeholder="Event title" value={form.title} onChange={e=>setForm({...form,title:e.target.value})}/><textarea required minLength={10} rows={4} className={field} placeholder="What happened, what was affected and what evidence is available?" value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/><Button disabled={busy} leftIcon={<AlertTriangle className="h-4 w-4"/>}>Record event</Button></form></Card>
  <Card><div className="flex items-center gap-2"><ShieldCheck className="h-5 w-5 text-royal-700"/><h3 className="font-bold">Security event queue</h3></div><div className="mt-4 space-y-3">{events.slice(0,12).map(e=><div key={e.id} className="rounded-xl border p-4"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="font-bold">{e.title}</p><p className="mt-1 text-xs capitalize text-muted">{e.event_number} · {e.product} · {e.event_type.replaceAll('_',' ')} · {fullName(personMap.get(e.actor_id||''))}</p></div><div className="flex gap-2">{badge(e.severity,tone(e.severity))}{badge(e.status,tone(e.status))}</div></div>{e.description&&<p className="mt-2 text-sm text-muted">{e.description}</p>}<div className="mt-3 flex flex-wrap gap-2">{!["resolved","dismissed"].includes(e.status)&&<><Button size="sm" variant="secondary" disabled={busy} onClick={()=>void updateEvent(e,"verified")}>Verify</Button><Button size="sm" variant="secondary" disabled={busy} onClick={()=>void updateEvent(e,"blocked")}>Mark blocked</Button>{!incidents.some(i=>i.event_id===e.id)&&<Button size="sm" disabled={busy} onClick={()=>void createIncident(e)}>Open incident</Button>}</>}</div></div>)}{!events.length&&<p className="py-8 text-center text-sm text-muted">No security events have been recorded.</p>}</div></Card></div>
  <Card><div className="flex items-center gap-2"><AlertTriangle className="h-5 w-5 text-rose-600"/><h3 className="font-bold">Incident response</h3></div><div className="mt-4 overflow-x-auto"><table className="w-full text-left text-sm"><thead className="bg-gray-50"><tr>{["Incident","Severity","Product","Assigned","Status","Opened"].map(x=><th key={x} className="p-3 text-xs uppercase text-muted">{x}</th>)}</tr></thead><tbody>{incidents.map(i=><tr key={i.id} className="border-t"><td className="p-3"><p className="font-bold">{i.title}</p><p className="text-xs text-muted">{i.incident_number}</p></td><td className="p-3">{badge(i.severity,tone(i.severity))}</td><td className="p-3 capitalize">{i.product}</td><td className="p-3">{fullName(personMap.get(i.assigned_to||''))}</td><td className="p-3"><select aria-label={`Status for ${i.incident_number}`} disabled={busy} value={i.status} onChange={e=>void updateIncident(i,e.target.value)} className="rounded-lg border bg-white px-2 py-2"><option value="open">Open</option><option value="investigating">Investigating</option><option value="contained">Contained</option><option value="resolved">Resolved</option><option value="closed">Closed</option></select></td><td className="p-3 text-muted">{new Date(i.created_at).toLocaleDateString("en-NG")}</td></tr>)}</tbody></table>{!incidents.length&&<p className="py-8 text-center text-sm text-muted">No security incidents are open.</p>}</div></Card>
  <Card><div className="flex items-center gap-2"><CheckCircle2 className="h-5 w-5 text-emerald-600"/><h3 className="font-bold">Recent protected audit activity</h3></div><div className="mt-4 grid gap-3 md:grid-cols-2">{logs.slice(0,10).map(a=><div key={a.id} className="rounded-xl border p-3"><p className="font-semibold">{a.action}</p><p className="mt-1 text-xs text-muted">{a.product||"system"} · {fullName(personMap.get(a.actor_id||''))} · {new Date(a.created_at).toLocaleString("en-NG")}</p></div>)}</div></Card>
 </ModulePage>;
}
