import {useCallback,useEffect,useRef,useState,type FormEvent} from 'react';
import {useAuth} from '@/context/AuthContext';
import {supabase} from '@/lib/supabase';
import {Card} from '@/components/ui/Card';
import {Button} from '@/components/ui/Button';
type Row=Record<string,any>;
const input='mt-2 block w-full rounded-xl border p-3';
export function BusinessOperationsPanel({unit}:{unit:string}){
 const {user,profile,adminAccess}=useAuth();const [data,setData]=useState<Record<string,Row[]>>({}),[tab,setTab]=useState('orders'),[error,setError]=useState(''),[busy,setBusy]=useState(false),[search,setSearch]=useState(''),[form,setForm]=useState<Row>({}),[loading,setLoading]=useState(true);
 const scope=useRef('');scope.current=`${user?.id}:${unit}`;
 const canEdit=(target:string)=>profile?.status==='active'&&(profile.role==='super_admin'||adminAccess.some(g=>[target,'business_centre'].includes(g.product)&&(g.can_edit||g.can_manage)));
 const tabs=[...(unit==='business_centre'?[['business_catalog','Service Catalogue'],['business_units','Business Units']]:[]),['orders','Requests'],['business_quotes','Quotes'],['business_invoices','Invoices'],['business_payments','Payment ledger'],['business_files','Files'],['business_support_tickets','Support'],...(unit==='fabrication'||unit==='business_centre'?[['fabrication_jobs','Fabrication jobs']]:[]),...(unit==='compute'||unit==='business_centre'?[['compute_jobs','Compute jobs'],['compute_usage_records','Usage']]:[]),...(unit==='academy'||unit==='business_centre'?[['academy_courses','Courses'],['academy_enrollments','Applications'],['academy_sessions','Schedule'],['academy_attendance','Attendance'],['academy_resources','Learning materials'],['academy_certificates','Certificates']]:[])];
 const load=useCallback(async()=>{if(!supabase)return {};const q=supabase.from('business_orders').select('*').order('created_at',{ascending:false});const r=await(unit==='business_centre'?q:q.eq('unit_code',unit));if(r.error)throw r.error;const result:Record<string,Row[]>={orders:r.data||[]};if(unit==='business_centre'){for(const table of ['business_catalog','business_units']){const z=await supabase.from(table).select('*').order('created_at',{ascending:false});if(z.error)throw z.error;result[table]=z.data||[];}}const ids=result.orders.map(x=>x.id);const queries:[string,PromiseLike<any>][]=[];
  if(ids.length)for(const table of ['business_quotes','business_invoices','business_files',...(unit==='fabrication'||unit==='business_centre'?['fabrication_jobs']:[]),...(unit==='compute'||unit==='business_centre'?['compute_jobs','compute_usage_records']:[])])queries.push([table,supabase.from(table).select('*').in('order_id',ids)]);
  const tickets=supabase.from('business_support_tickets').select('*');queries.push(['business_support_tickets',unit==='business_centre'?tickets:tickets.eq('unit_code',unit)]);
  if(unit==='academy'||unit==='business_centre')for(const table of ['academy_courses','academy_enrollments','academy_sessions','academy_attendance','academy_resources','academy_certificates'])queries.push([table,supabase.from(table).select('*')]);
  await Promise.all(queries.map(async([key,query])=>{const x=await query;if(x.error)throw x.error;result[key]=x.data||[];}));const invoiceIds=(result.business_invoices||[]).map(x=>x.id);if(invoiceIds.length){const p=await supabase.from('business_payments').select('*').in('invoice_id',invoiceIds);if(p.error)throw p.error;result.business_payments=p.data||[];}return result;
 },[unit,user?.id]);
 useEffect(()=>{let active=true;setData({});setError('');setForm({});setTab('orders');setLoading(true);void load().then(x=>{if(active)setData(x);}).catch(e=>{if(active)setError(e.message);}).finally(()=>{if(active)setLoading(false);});return()=>{active=false;};},[load]);
 async function action(work:()=>Promise<void>){if(busy)return;const key=scope.current;setBusy(true);setError('');try{await work();const next=await load();if(key===scope.current){setData(next);setForm({});}}catch(e){if(key===scope.current)setError(e instanceof Error?e.message:'Could not save.');}finally{if(key===scope.current)setBusy(false);}}
 async function update(table:string,id:string,values:Row){await action(async()=>{const r=await supabase!.from(table).update(values).eq('id',id).select('id');if(r.error)throw r.error;if(!r.data?.length)throw new Error('The record was not changed. Check permissions and refresh.');});}
 const fields:Record<string,[string,string,string?][]>={business_quotes:[['amount','Approved quote amount','number'],['notes','Costing and specifications'],['valid_until','Valid until','date']],business_invoices:[['amount','Invoice amount','number'],['due_at','Due date','date']],academy_courses:[['title','Course title'],['slug','URL slug'],['category','Category'],['description','Description'],['duration_text','Duration'],['fee','Approved fee (optional)','number']],academy_sessions:[['title','Session title'],['starts_at','Starts','datetime-local'],['ends_at','Ends','datetime-local'],['venue','Venue'],['meeting_url','Meeting URL','url']],academy_resources:[['title','Material title'],['resource_url','HTTPS learning material URL','url'],['due_at','Due date','datetime-local']],academy_attendance:[['notes','Attendance notes']],compute_usage_records:[['hours','Verified hours','number'],['credits_used','Verified credits used','number'],['started_at','Started','datetime-local'],['ended_at','Ended','datetime-local'],['notes','Usage notes']]};
 const order=(data.orders||[]).find(x=>x.id===form.order_id),enrollment=(data.academy_enrollments||[]).find(x=>x.id===form.enrollment_id);
 const mayCompose=canEdit(unit)||(unit==='business_centre'&&adminAccess.some(g=>['academy','fabrication','compute','digital_business'].includes(g.product)&&(g.can_edit||g.can_manage)));
 const editable=canEdit(tab.startsWith('academy_')?'academy':tab==='compute_usage_records'?'compute':order?.unit_code||unit);
 async function create(e:FormEvent){e.preventDefault();await action(async()=>{if(!editable)throw new Error('Edit permission required.');let values:Row={};
  if(tab==='business_catalog')values={unit_code:'business_centre',name:form.name,slug:form.slug,category:form.category,description:form.description||null,base_price:Number(form.base_price||0),pricing_unit:form.pricing_unit||'service',features:[],is_active:false};
  else if(tab==='business_quotes'||tab==='business_invoices'){if(!order||!(Number(form.amount)>0))throw new Error('Select a request and enter a positive approved amount.');values={order_id:order.id,amount:Number(form.amount),currency:'NGN',status:'issued',...(tab==='business_quotes'?{notes:form.notes||null,valid_until:form.valid_until||null}:{due_at:form.due_at||null})};}
  else if(tab==='academy_courses')values={title:form.title,slug:form.slug,category:form.category,description:form.description||null,duration_text:form.duration_text||null,fee:form.fee?Number(form.fee):null,delivery_mode:form.delivery_mode||'hybrid',is_active:form.is_active==='yes'};
  else if(tab==='academy_sessions')values={course_id:form.course_id,title:form.title,starts_at:new Date(form.starts_at).toISOString(),ends_at:form.ends_at?new Date(form.ends_at).toISOString():null,venue:form.venue||null,meeting_url:form.meeting_url||null,status:'scheduled'};
  else if(tab==='academy_resources')values={course_id:form.course_id,title:form.title,resource_url:form.resource_url,resource_type:form.resource_type||'resource',due_at:form.due_at?new Date(form.due_at).toISOString():null};
  else if(tab==='academy_attendance')values={enrollment_id:form.enrollment_id,session_id:form.session_id,status:form.status||'present',notes:form.notes||null};
  else if(tab==='compute_usage_records')values={order_id:form.order_id,hours:Number(form.hours),credits_used:Number(form.credits_used||0),started_at:form.started_at?new Date(form.started_at).toISOString():null,ended_at:form.ended_at?new Date(form.ended_at).toISOString():null,notes:form.notes||null};
  const r=await supabase!.from(tab).insert(values);if(r.error)throw r.error;});}
 const select=(key:string,title:string,choices:Row[],display:(x:Row)=>string)=><label className="block">{title}<select required className={input} value={form[key]||''} onChange={e=>setForm({...form,[key]:e.target.value})}><option value="">Choose {title.toLowerCase()}</option>{choices.map(x=><option key={x.id} value={x.id}>{display(x)}</option>)}</select></label>;
 const rows=(data[tab]||[]).filter(x=>Object.values(x).some(v=>String(v??'').toLowerCase().includes(search.toLowerCase())));
 return <><nav aria-label="Business operations" className="mb-5 flex flex-wrap gap-2">{tabs.map(([key,title])=><button key={key} onClick={()=>{setTab(key);setForm({});setSearch('');}} className={'rounded-xl border px-4 py-2 text-sm font-bold '+(tab===key?'bg-royal-600 text-white':'bg-white')}>{title}</button>)}</nav><div className="mb-5 flex items-end gap-3"><label className="grow">Search records<input className={input} type="search" value={search} onChange={e=>setSearch(e.target.value)}/></label><Button variant="secondary" onClick={()=>window.print()}>Print / save PDF</Button></div>{error&&<p role="alert" className="mb-4 rounded-xl bg-rose-50 p-4 text-rose-700">{error}</p>}
 {fields[tab]&&mayCompose&&<Card className="mb-6"><h2 className="font-bold">Create approved record</h2><form className="mt-4 grid gap-4 md:grid-cols-2" onSubmit={e=>void create(e)}>{['business_quotes','business_invoices','compute_usage_records'].includes(tab)&&select('order_id','Request',(data.orders||[]).filter(x=>tab!=='compute_usage_records'||x.unit_code==='compute'),x=>x.order_number+' — '+x.title)}{['academy_sessions','academy_resources'].includes(tab)&&select('course_id','Course',data.academy_courses||[],x=>x.title)}{tab==='academy_attendance'&&<>{select('enrollment_id','Enrolment',data.academy_enrollments||[],x=>x.user_id+' · '+((data.academy_courses||[]).find(c=>c.id===x.course_id)?.title||''))}{select('session_id','Session',(data.academy_sessions||[]).filter(s=>s.course_id===enrollment?.course_id),x=>x.title)}<label>Attendance<select className={input} value={form.status||'present'} onChange={e=>setForm({...form,status:e.target.value})}><option>present</option><option>absent</option><option>excused</option></select></label></>}{fields[tab].map(([key,title,type])=><label key={key}>{title}<input className={input} type={type||'text'} min={type==='number'?'0':undefined} step={type==='number'?'0.01':undefined} required={['amount','title','slug','category','resource_url','hours','starts_at'].includes(key)} value={form[key]||''} onChange={e=>setForm({...form,[key]:e.target.value})}/></label>)}{tab==='academy_courses'&&<><label>Delivery<select className={input} value={form.delivery_mode||'hybrid'} onChange={e=>setForm({...form,delivery_mode:e.target.value})}><option>hybrid</option><option>online</option><option>physical</option></select></label><label>Publish approved course<select className={input} value={form.is_active||'no'} onChange={e=>setForm({...form,is_active:e.target.value})}><option value="no">Keep inactive</option><option value="yes">Publish</option></select></label></>}{tab==='academy_resources'&&<label>Material type<select className={input} value={form.resource_type||'resource'} onChange={e=>setForm({...form,resource_type:e.target.value})}><option>resource</option><option>assignment</option></select></label>}<Button disabled={busy||!editable}>{busy?'Saving…':'Save record'}</Button></form></Card>}
 {loading?<p role="status">Loading authorized records…</p>:<div className="space-y-4">{rows.map(x=>{const request=(data.orders||[]).find(o=>o.id===x.order_id);const edit=canEdit(tab.startsWith('academy_')?'academy':x.unit_code||request?.unit_code||unit);return <Card key={x.id}><h2 className="font-bold">{x.title||x.order_number||x.quote_number||x.invoice_number||x.file_name||x.subject||x.certificate_code||x.workload_type||x.process||x.id}</h2><dl className="mt-3 grid gap-3 text-sm md:grid-cols-3">{Object.entries(x).filter(([key,v])=>!['id','user_id','order_id','course_id','file_url','storage_path'].includes(key)&&v!=null).map(([key,v])=><div key={key}><dt className="text-xs text-muted">{key.replaceAll('_',' ')}</dt><dd className="mt-1 break-words">{typeof v==='object'?JSON.stringify(v):String(v)}</dd></div>)}</dl>
 {tab==='business_catalog'&&edit&&<Button className="mt-4" disabled={busy} onClick={()=>void update(tab,x.id,{is_active:!x.is_active,updated_at:new Date().toISOString()})}>{x.is_active?'Hide service':'Publish service'}</Button>}
 {tab==='business_units'&&edit&&<Button className="mt-4" disabled={busy} onClick={()=>void update(tab,x.id,{status:x.status==='active'?'inactive':'active',updated_at:new Date().toISOString()})}>{x.status==='active'?'Disable unit':'Enable unit'}</Button>}
 {tab==='orders'&&edit&&<div className="mt-4 flex gap-2">{x.status==='submitted'&&<Button disabled={busy} onClick={()=>void update('business_orders',x.id,{status:'reviewing'})}>Review</Button>}{['reviewing','paid'].includes(x.status)&&(data.business_invoices||[]).some(i=>i.order_id===x.id&&i.status==='paid')&&<Button disabled={busy} onClick={()=>void update('business_orders',x.id,{status:'in_progress'})}>Start paid request</Button>}{x.status==='in_progress'&&<Button disabled={busy} onClick={()=>void update('business_orders',x.id,{status:'completed'})}>Confirm completion</Button>}</div>}
 {tab==='fabrication_jobs'&&edit&&<div className="mt-4 space-y-3"><form className="grid gap-3 md:grid-cols-2" onSubmit={e=>{e.preventDefault();const values=new FormData(e.currentTarget);void update(tab,x.id,{process:String(values.get('process')||''),material:String(values.get('material')||''),dimensions:String(values.get('dimensions')||''),machine_notes:String(values.get('machine_notes')||'')});}}><label>Process<input name="process" className={input} defaultValue={x.process||''}/></label><label>Material<input name="material" className={input} defaultValue={x.material||''}/></label><label>Dimensions / specification<input name="dimensions" className={input} defaultValue={x.dimensions||''}/></label><label>Production / quality notes<textarea name="machine_notes" className={input} defaultValue={x.machine_notes||''}/></label><Button disabled={busy}>Save fabrication details</Button></form>{request&&<div className="flex flex-wrap gap-2">{request.status==='submitted'&&<Button disabled={busy} onClick={()=>void update('business_orders',request.id,{status:'reviewing'})}>Move to review</Button>}{request.status==='reviewing'&&(data.business_invoices||[]).some(i=>i.order_id===request.id&&i.status==='paid')&&<Button disabled={busy} onClick={()=>void update('business_orders',request.id,{status:'in_progress'})}>Start paid fabrication</Button>}{request.status==='in_progress'&&<Button disabled={busy} onClick={()=>void update('business_orders',request.id,{status:'completed'})}>Complete quality check & handover</Button>}</div>}</div>}
 {tab==='business_files'&&x.storage_path&&<Button className="mt-4" disabled={busy} onClick={()=>void action(async()=>{const r=await supabase!.storage.from('business-files').createSignedUrl(x.storage_path,60);if(r.error)throw r.error;const a=document.createElement('a');a.href=r.data.signedUrl;a.target='_blank';a.rel='noopener noreferrer';a.click();})}>Open private file</Button>}
 {tab==='academy_courses'&&edit&&<Button className="mt-4" disabled={busy} onClick={()=>void update(tab,x.id,{is_active:!x.is_active})}>{x.is_active?'Unpublish':'Publish approved course'}</Button>}
 {tab==='academy_enrollments'&&edit&&<div className="mt-4 flex flex-wrap gap-3">{['applied','enrolled'].includes(x.status)&&<Button disabled={busy} onClick={()=>void update(tab,x.id,{status:x.status==='applied'?'enrolled':'active'})}>{x.status==='applied'?'Approve enrolment':'Activate learning'}</Button>}{x.status==='active'&&<Button disabled={busy} onClick={()=>void update(tab,x.id,{status:'completed',progress:100,completed_at:new Date().toISOString()})}>Confirm assessed completion</Button>}{x.status==='completed'&&x.progress===100&&!(data.academy_certificates||[]).some(c=>c.enrollment_id===x.id)&&<Button disabled={busy} onClick={()=>void action(async()=>{const r=await supabase!.from('academy_certificates').insert({enrollment_id:x.id});if(r.error)throw r.error;})}>Issue certificate</Button>}</div>}
 {tab==='academy_certificates'&&edit&&x.status==='issued'&&<Button className="mt-4" disabled={busy} onClick={()=>void update(tab,x.id,{status:'revoked'})}>Revoke certificate</Button>}
 {tab==='business_support_tickets'&&edit&&<form className="mt-4 space-y-3" onSubmit={e=>{e.preventDefault();const fields=new FormData(e.currentTarget);void update(tab,x.id,{admin_response:String(fields.get('response')),status:String(fields.get('status'))});}}><label>Reply<textarea required name="response" className={input} defaultValue={x.admin_response||''}/></label><label>Ticket status<select name="status" className={input} defaultValue={x.status}><option>open</option><option>in_progress</option><option>resolved</option></select></label><Button disabled={busy}>Save reply</Button></form>}
 </Card>;})}{!rows.length&&<p className="rounded-xl border bg-slate-50 p-5 text-sm">No authorized records match this view.</p>}</div>}</>;
}
